### ISSUE TITLE
Authentication failed github desktop

### ISSUE THREAD

**Issue by kasun-sonic-devs** [shiftkey/desktop#1016]
### The problem

When I clone my organization repository show Authentication failed message and I give username and password correctly after save and retry again failed
![Screenshot from 2024-02-29 01-50-06](https://github.com/shiftkey/desktop/assets/110441833/8b6f7679-c2a2-4afb-a474-332db823aacd)

### Release version

Version 3.3.8-linux2 (x64)

### Operating system

Ubuntu 22.04.4 LTS

### Steps to reproduce the behavior

![Screenshot from 2024-02-29 01-50-06](https://github.com/shiftkey/desktop/assets/110441833/64219fb9-d7f1-4e60-aa79-4ca23eb34766)

### Log files

[2024-02-28.desktop..log](https://github.com/shiftkey/desktop/files/14439588/2024-02-28.desktop.log)
[2024-02-28.desktop.production.log](https://github.com/shiftkey/desktop/files/14439589/2024-02-28.desktop.production.log)

**Comment by shiftkey** [comment]
```
2024-02-28T19:35:22.527Z - error: [ui] Failed to look up canonical clone url for 'https://github.com/Sonic-Labs/meththa-frontend.git'
Error: Although you appear to have the correct authorization credentials, the `Sonic-Labs` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ve (/home/kasun/webpack:/app/src/lib/http.ts:170:11)
    at ut.fetchRepositoryCloneUrl (/home/kasun/webpack:/app/src/lib/api.ts:620:11)
    at qv.resolveCloneURL (/home/kasun/webpack:/app/src/ui/clone-repository/clone-repository.tsx:614:7)
    at Object.clone [as onSubmit] (/home/kasun/webpack:/app/src/ui/clone-repository/clone-repository.tsx:631:11)
```
