### ISSUE TITLE
Authentication Failure during cloning a repo 

### ISSUE THREAD

**Issue by DurgaVikas** [shiftkey/desktop#1042]
### The problem

I have been trying to clone a repo from my organization using github desktop but the autentication failure is raised even with correct credentials. I have logout from github desktop and try again same error is raising solve this issue ASAP.

### Release version

Version 3.3.12-linux2 (x64)

### Operating system

Fedora 39

### Steps to reproduce the behavior

1. Open Github Desktop and select file 
2. In file,select clone repository
3. Select a repo from your organization
4. Then the authentication failure occurs

### Log files

[2024-04-08.desktop..log](https://github.com/shiftkey/desktop/files/14901611/2024-04-08.desktop.log)

### Screenshots

![Screenshot from 2024-04-08 10-42-16](https://github.com/shiftkey/desktop/assets/103378844/42a746e2-c27b-41e8-a159-041bfad237ce)

**Comment by shiftkey** [comment]
```
024-04-08T06:01:22.587Z - error: [ui] Failed to look up repository clone info for 'https://github.com/deepfacts/prorithm_ads.git'
Error: Although you appear to have the correct authorization credentials, the `deepfacts` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at fn (/home/durgavikas/webpack:/app/src/lib/http.ts:178:11)
    at nr.fetchRepositoryCloneInfo (/home/durgavikas/webpack:/app/src/lib/api.ts:984:11)
    at Object.clone [as onSubmit] (/home/durgavikas/webpack:/app/src/ui/clone-repository/clone-repository.tsx:727:11)
```

**Comment by ilkinnezer1** [comment]
I am facing with this issue as well. Do you know how to fix it?

UPDATE:
cloning via ssh fixed this issue.

**Comment by migueloliveiraweb** [comment]
I am facing this problem too. Does anyone have a solution for this?

**Comment by ilkinnezer1** [comment]
> I am facing this problem too. Does anyone have a solution for this?

Use SSH, it will fix it

**Comment by migueloliveiraweb** [comment]
How can I use SSH to fix it?

**Comment by ilkinnezer1** [comment]
> How can I use SSH to fix it?

You can generate ssh, add it to the Github and try to clone with ssh on Github Desktop, there is an option there
