### ISSUE TITLE
Authentication Failed While Cloning Project

### ISSUE THREAD

**Issue by devmdeniz** [shiftkey/desktop#1043]
### The problem

I logged into Github Desktop and all my projects are showing up, such as projects in private status, projects in different organizations. When I tried to do the clone process, I got the warning "We were unable to authenticate with github.com. Please enter your username and password to try again." I got a warning.

```
2024-04-09T10:11:56.675Z - info: [ui] [AppStore] loading 0 repositories from store
2024-04-09T10:11:56.789Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-04-09T10:11:56.790Z - info: [ui] launching: 3.3.12-linux2 (Linux 6.8.2-arch2-1)
2024-04-09T10:11:56.791Z - info: [ui] execPath: '/opt/github-desktop/github-desktop'
2024-04-09T10:11:56.812Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-04-09T10:11:57.327Z - info: [ui] Opt in reported.
2024-04-09T10:12:00.231Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
2024-04-09T10:12:00.235Z - info: [ui] [SignInStore] initializing OAuth flow
2024-04-09T10:12:00.246Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=dac41738-76a2-4b71-bf20-5b47eaef3d17
2024-04-09T10:12:00.248Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2024-04-09T10:12:00.427Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2024-04-09T10:12:03.157Z - info: [main] Received possible protocol arguments: 3
2024-04-09T10:12:03.157Z - info: [main] Processing protocol url
2024-04-09T10:12:03.158Z - info: [ui] [Dispatcher] requesting authenticated user
2024-04-09T10:12:03.159Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2024-04-09T10:12:03.253Z - info: [main] Received possible protocol arguments: 2
2024-04-09T10:12:03.284Z - info: [main] Processing protocol url
2024-04-09T10:12:09.464Z - info: [ui] [SignInStore] account resolved
2024-04-09T10:12:09.465Z - info: [ui] [AppStore] adding account devmdeniz (Mehmet Deniz Kumcu) to store
2024-04-09T10:12:09.469Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2024-04-09T10:12:09.516Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-04-09T10:12:10.008Z - info: [ui] Subscribed 'devmdeniz' to Alive channel
2024-04-09T10:12:10.220Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-04-09T10:12:59.428Z - error: [ui] Failed to look up repository clone info for 'https://github.com/Papitya-Bilisim/Panel.greenmenajerlik.com.git'
Error: Although you appear to have the correct authorization credentials, the `Papitya-Bilisim` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at fn (/home/devmdeniz/webpack:/app/src/lib/http.ts:178:11)
    at nr.fetchRepositoryCloneInfo (/home/devmdeniz/webpack:/app/src/lib/api.ts:984:11)
    at Object.clone [as onSubmit] (/home/devmdeniz/webpack:/app/src/ui/clone-repository/clone-repository.tsx:727:11)
2024-04-09T10:12:59.429Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/Papitya-Bilisim/Panel.greenmenajerlik.com.git - devmdeniz (has token)
2024-04-09T10:13:00.478Z - info: [ui] Executing clone: git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/Papitya-Bilisim/Panel.greenmenajerlik.com.git /opt/lampp/htdocs/Panel.greenmenajerlik.com (took 1.033s)
2024-04-09T10:13:00.480Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/Papitya-Bilisim/Panel.greenmenajerlik.com.git /opt/lampp/htdocs/Panel.greenmenajerlik.com` exited with an unexpected code: 128.
stderr:
Cloning into '/opt/lampp/htdocs/Panel.greenmenajerlik.com'...
remote: Repository not found.
fatal: repository 'https://github.com/Papitya-Bilisim/Panel.greenmenajerlik.com.git/' not found

(The error was parsed as 9: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2024-04-09T10:13:41.269Z - error: [ui] Failed to look up repository clone info for 'https://github.com/Papitya-Bilisim/Panel.greenmenajerlik.com.git'
Error: Although you appear to have the correct authorization credentials, the `Papitya-Bilisim` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at fn (/home/devmdeniz/webpack:/app/src/lib/http.ts:178:11)
    at nr.fetchRepositoryCloneInfo (/home/devmdeniz/webpack:/app/src/lib/api.ts:984:11)
    at Object.clone [as onSubmit] (/home/devmdeniz/webpack:/app/src/ui/clone-repository/clone-repository.tsx:727:11)
2024-04-09T10:13:41.270Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/Papitya-Bilisim/Panel.greenmenajerlik.com.git - devmdeniz (has token)
2024-04-09T10:13:42.909Z - info: [ui] Executing clone: git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/Papitya-Bilisim/Panel.greenmenajerlik.com.git /home/devmdeniz/Desktop/Github/Panel.greenmenajerlik.com (took 1.598s)
2024-04-09T10:13:42.911Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/Papitya-Bilisim/Panel.greenmenajerlik.com.git /home/devmdeniz/Desktop/Github/Panel.greenmenajerlik.com` exited with an unexpected code: 128.
stderr:
Cloning into '/home/devmdeniz/Desktop/Github/Panel.greenmenajerlik.com'...
remote: Repository not found.
fatal: repository 'https://github.com/Papitya-Bilisim/Panel.greenmenajerlik.com.git/' not found

(The error was parsed as 9: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2024-04-09T10:14:11.067Z - info: [ui] storing generic credentials for 'github.com' and 'devmdeniz'
2024-04-09T10:14:11.086Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/Papitya-Bilisim/Panel.greenmenajerlik.com.git - devmdeniz (has token)
2024-04-09T10:14:11.968Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/Papitya-Bilisim/Panel.greenmenajerlik.com.git /home/devmdeniz/Desktop/Github/Panel.greenmenajerlik.com` exited with an unexpected code: 128.
stderr:
Cloning into '/home/devmdeniz/Desktop/Github/Panel.greenmenajerlik.com'...
remote: Repository not found.
fatal: repository 'https://github.com/Papitya-Bilisim/Panel.greenmenajerlik.com.git/' not found

(The error was parsed as 9: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2024-04-09T10:17:02.105Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.com/api/v3/meta' as a fallback
Error: API error https://github.com/api/v3/meta:  (404)
    at fn (/home/devmdeniz/webpack:/app/src/lib/http.ts:178:11)
    at /home/devmdeniz/webpack:/app/src/lib/api.ts:2045:11
    at Kp.endpointSupportsBasicAuth (/home/devmdeniz/webpack:/app/src/lib/stores/sign-in-store.ts:255:11)
    at Kp.setEndpoint (/home/devmdeniz/webpack:/app/src/lib/stores/sign-in-store.ts:549:13)
2024-04-09T10:17:40.701Z - info: [ui] [AppStore] loading 0 repositories from store
2024-04-09T10:17:40.705Z - info: [ui] [AppStore] found account: devmdeniz (Mehmet Deniz Kumcu)
2024-04-09T10:17:40.745Z - info: [ui] launching: 3.3.12-linux2 (Linux 6.8.2-arch2-1)
2024-04-09T10:17:40.746Z - info: [ui] execPath: '/opt/github-desktop/github-desktop'
2024-04-09T10:17:41.370Z - info: [ui] Stats reported.
2024-04-09T10:17:41.433Z - info: [ui] Subscribed 'devmdeniz' to Alive channel
2024-04-09T10:18:00.000Z - info: [main] opening in browser: https://github.com/shiftkey/desktop/releases/
```
There is logs

### Release version

3.3.12.linux2 (x64)

### Operating system

Arch Linux

### Steps to reproduce the behavior

1. Clone Project
2. Error

### Log files

[2024-04-09.desktop..log](https://github.com/shiftkey/desktop/files/14917403/2024-04-09.desktop.log)

**Comment by shiftkey** [comment]
> `Error: Although you appear to have the correct authorization credentials, the `Papitya-Bilisim` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/`

**Comment by pixelbart** [comment]
> > `Error: Although you appear to have the correct authorization credentials, the `Papitya-Bilisim` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/`

Thank you! <3
