### ISSUE TITLE
Random write error exception

### ISSUE THREAD

**Issue by aminya** [shiftkey/desktop#1097]
### The problem

I've been getting this random write-error exception.

```
Error: EIO: i/o error, write
    at writeSync (node:fs:931:3)
    at SyncWriteStream._write (node:internal/fs/sync_write_stream:27:5)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at SyncWriteStream.Writable.write (node:internal/streams/writable:502:10)
    at console.value (node:internal/console/constructor:304:16)
    at console.warn (node:internal/console/constructor:384:26)
    at f.log (app/src/main-process/desktop-console-transport.ts:41:7)
    at f.s._write (app/node_modules/winston-transport/index.js:82:19)
    at O (app/node_modules/readable-stream/lib/_stream_writable.js:409:139)

Version: 3.4.2-linux1
OS: Linux 6.5.0-41-generic
```

### Release version

3.4.2-linux1

### Operating system

 Linux 6.5.0-41-generic

### Screenshots

![image](https://github.com/shiftkey/desktop/assets/16418197/0cd9c249-1969-4d86-a75d-005c0ffaa5a1)

### Additional context

 I maintain some of my repositories on an external drive that is not always mounted.

**Comment by shiftkey** [comment]
The mention of `winston-transport` is related to logs, and I wonder if there's something related to where logs are being written to that would explain this error. `~/.config/GitHub Desktop/logs/` is where logs are written to - is there something unexpected about your setup that might suggest that this directory is not present?
