### ISSUE TITLE
Private repositories seen as "Other" and not GitHub

### ISSUE THREAD

**Issue by mitar** [shiftkey/desktop#24]
Adding private repositories are added as "Other" and not GitHub.

This is  follow up to https://github.com/desktop/desktop/issues/3568.

With 1.0.12 Linux RC1.

I cleared all my databases as instructed. I am not getting anymore any visible error in UI, but just private repositories are not recognized as GitHub repositories. I can still pull and push normally (probably because it goes over SSH).

**Comment by shiftkey** [comment]
@mitar please provide a fresh log file and the `git remote -vv` of the problem repositories so we can troubleshoot further.

**Comment by mitar** [comment]
Hm, because they are private repos, I am not completely sure I want to share info publicly?

**Comment by shiftkey** [comment]
@mitar you can send sensitive stuff through the email address in my profile, if that helps

**Comment by mitar** [comment]
I can maybe just change URIs, if this is OK with you? Or do you have to know which repositories are involved?

**Comment by shiftkey** [comment]
@mitar the URLs are somewhat important, but we can try them being renamed as long as they match the _structure_ of the real URLs

**Comment by mitar** [comment]
Log when adding a private repo:

```
2018-01-16T06:45:55.077Z - warn: [ui] fetchRepository: 'private/example' returned a 404
2018-01-16T06:46:24.033Z - info: [ui] [AppStore] adding repository at /home/user/example to store
2018-01-16T06:46:24.684Z - warn: [ui] fetchRepository: 'private/example' returned a 404
2018-01-16T06:46:24.747Z - warn: [ui] Unable to fetch issues for private/example
Error: Cannot get issues for a repository that hasn't been inserted into the database!
    at Object.n [as fatalError] (/home/user/webpack:/external "path":1:1)
    at t.IssuesStore.getLatestUpdatedAt (/home/user/webpack:/app/src/lib/stores/issues-store.ts:29:24)
    at t.IssuesStore.fetchIssues (/home/user/webpack:/app/src/lib/stores/issues-store.ts:66:5)
    at oe._updateIssues (/home/user/webpack:/app/src/lib/stores/app-store.ts:830:6)
    at oe._selectRepository (/home/user/webpack:/app/src/lib/stores/app-store.ts:799:5)
    at t.Dispatcher.selectRepository (/home/user/webpack:/app/src/lib/dispatcher/dispatcher.ts:167:4)
    at addRepository (/home/user/webpack:/app/src/ui/add-repository/add-existing-repository.tsx:185:3)
    at <anonymous>
2018-01-16T06:46:25.283Z - warn: [ui] fetchRepository: 'private/example' returned a 404
2018-01-16T06:46:26.903Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.923s)
```

```
$ git remote -vv
origin	git@github.com:private/example.git (fetch)
origin	git@github.com:private/example.git (push)
```

**Comment by shiftkey** [comment]
I'm going to close this out because I don't have the bandwidth currently to investigate what this might have been - apologies @mitar! 

My best guess is related to this line:

```
2018-01-16T06:46:25.283Z - warn: [ui] fetchRepository: 'private/example' returned a 404
```

This is our lookup for the repository using the GitHub API, and it is most likely failing in this way as no user token is sent by the app (this should be created on login and persisted to credential storage) and so the API doesn't respond to a request for a private repository (and the app wouldn't consider it a GitHub repository).

We have some better tracing in the app these days to detect when it can't find a token, and if you have SSH authentication configured correctly this is probably the only time you'd notice this issue.
