### ISSUE TITLE
Github Dekstop Crashes on relocating repo after moving repo directory in Linux

### ISSUE THREAD

**Issue by bhavik2936** [shiftkey/desktop#356]
### Description of the bug

After moving repository directory to another directory the **Locate** button leads to crash Github Desktop

### Version & OS

Github Desktop: 2.0.4-linux1
OS: Ubuntu 20.04.1 LTS

### Steps to reproduce the behavior

1. Open Github Dekstop
2. Clone any repository
3. Locate repository in File Manager
4. move whole directory folder to another direoctory
5. Github Desktop shows the **Locate** repository button now
6. As clicking on **Locate** button crashes the Github Desktop

### Expected behavior

Github Desktop should open the Folder Browser Dialog to relocate moved repository.

### Actual behavior

As described above the application gets crashed.

### Screenshots

Github Desktop opened [view image][1]
Github Desktop Locate button pressed [view image][2]
Github Desktop crashed [view image][3]

### Logs
I found the log with some error in it
```
2020-10-06T18:05:39.943Z - info: [ui] execPath: '/snap/github-desktop/x1/app/github-desktop'
2020-10-06T18:20:59.832Z - error: [ui] Error performing periodic fetch for 'nikhil1999/BAPS'
Error: Unable to find path to repository on disk.
    at /home/bhavik2936/webpack:/app/node_modules/dugite/build/lib/git-process.js:87:1
    at exithandler (child_process.js:310:5)
    at ChildProcess.errorhandler (child_process.js:322:5)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

But I repeated steps for crashing the application, I found only these many longs.
No more error printing for repetitive application crash
```
2020-10-06T18:32:05.528Z - info: [ui] [AppStore] loading 1 repositories from store
2020-10-06T18:32:05.529Z - info: [ui] [AppStore] found account: bhavik2936 (Bhavik Parmar)
2020-10-06T18:32:05.529Z - info: [ui] [AppStore] found account: bhavik2936 (Bhavik Parmar)
2020-10-06T18:32:05.805Z - info: [ui] launching: 2.0.4-linux1 (Linux 5.4.0-47-generic)
2020-10-06T18:32:05.806Z - info: [ui] execPath: '/snap/github-desktop/x1/app/github-desktop'
```

[1]: https://ibb.co/VCzYyRY
[2]: https://ibb.co/dMgWt73
[3]: https://ibb.co/fHQkcML

**Comment by bhavik2936** [comment]
The same happens for adding existing repository

**Comment by bala** [comment]
> ### Description of the bug
> 
> After moving repository directory to another directory the **Locate** button leads to crash Github Desktop
> ### Version & OS
> 
> Github Desktop: 2.0.4-linux1
> OS: Ubuntu 20.04.1 LTS

The latest version of Github Desktop for linux is 2.5.4. I tried to reproduce your error on ubuntu 20.04 on Github Desktop 2.5.4. It is working fine. I suggest you to update to latest version of App

**Comment by bhavik2936** [comment]
Thank You, Sure it was due to the older version of application.

This happened because the application was installed via snapd and now no longer providing support.
