### ISSUE TITLE
Install fails on armv7l

### ISSUE THREAD

**Issue by Regaddi** [shiftkey/desktop#468]
### Operating System/Distribution

Raspbian GNU/Linux 10 (buster) on a Raspberry Pi 400

### Installer

I'm trying to build from source, since the provided `.deb` doesn't work (it required amd64 packages, which are not installable).

### What happened?

```
$ sudo apt install ./Downloads/GitHubDesktop-linux-2.6.6-linux1.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'github-desktop:amd64' instead of './Downloads/GitHubDesktop-linux-2.6.6-linux1.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 github-desktop:amd64 : Depends: libgtk-3-0:amd64 but it is not installable
                        Depends: libnotify4:amd64 but it is not installable
                        Depends: libnss3:amd64 but it is not installable
                        Depends: libxtst6:amd64 but it is not installable
                        Depends: libatspi2.0-0:amd64 but it is not installable
                        Depends: libdrm2:amd64 but it is not installable
                        Depends: libgbm1:amd64 but it is not installable
                        Depends: libxcb-dri3-0:amd64 but it is not installable
                        Depends: libcurl3:amd64 but it is not installable or
                                 libcurl4:amd64 but it is not installable
                        Depends: libsecret-1-0:amd64 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

When trying to install all dependencies via `yarn`, the `postinstall` hook fails building `desktop-trampoline`;

```
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
[1/6] \u2810 desktop-trampoline
[2/6] \u2810 dugite
[3/6] \u2808 fs-admin
[6/6] \u2808 highlight.js
error /home/pi/GitHub/shiftkey-desktop/app/node_modules/desktop-trampoline: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/pi/GitHub/shiftkey-desktop/app/node_modules/desktop-trampoline
Output:
/bin/sh: 1: prebuild-install: not found
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.24.0 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/share/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/GitHub/shiftkey-desktop/app/node_modules/desktop-trampoline/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.node-gyp/11.1.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.node-gyp/11.1.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.node-gyp/11.1.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/GitHub/shiftkey-desktop/app/node_modules/desktop-trampoline',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/GitHub/shiftkey-desktop/app/node_modules/desktop-trampoline/build'
  CC(target) Release/obj.target/desktop-trampoline/src/desktop-trampoline.o
cc: error: unrecognized command line option '-m64'
make: *** [desktop-trampoline.target.mk:108: Release/obj.target/desktop-trampoline/src/desktop-trampoline.o] Error 1
make: Leaving directory '/home/pi/GitHub/shiftkey-desktop/app/node_modules/desktop-trampoline/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.10.17-v7l+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/GitHub/shiftkey-desktop/app/node_modules/desktop-trampoline
```

**Comment by shiftkey** [comment]
This is not supported currently, and #251 covers what needs to be supported in terms of upstream dependencies before an ARM-compatible version can be tested.

Please follow along with that issue in the meantime.
