### ISSUE TITLE
Cannot Sign in 

### ISSUE THREAD

**Issue by Sawaya-ui** [shiftkey/desktop#481]
Every time I log in, i.e. nominally via the settings, only my own repositories are displayed, but no others from other organizations. And when I try to clone a repository of mine from a private organization that I own then there is always that I have to log in and if I do that then it only loads for a while and then I have to log in again I have done it with the Github tokens and with normal login data.

### Version & OS

Kali Linux | Newest Version (2.7.2)

### Logs

2021-04-17T01:47:12.593Z - info: [ui] storing generic credentials for 'github.com' and 'Tgg1337'
2021-04-17T01:47:12.699Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/Rising-Phoenix-Development/rpd-official-new.git - Tgg1337 (has token)
2021-04-17T01:49:07.818Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/Rising-Phoenix-Development/rpd-official-new.git /media/tay/Gaming HDD 1TB/Development/Bots/rpd-official-new (took 115.060s)
2021-04-17T01:49:07.836Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/Rising-Phoenix-Development/rpd-official-new.git /media/tay/Gaming HDD 1TB/Development/Bots/rpd-official-new` exited with an unexpected code: 128.
stderr:
Cloning into '/media/tay/Gaming HDD 1TB/Development/Bots/rpd-official-new'...
remote: Repository not found.
fatal: repository 'https://github.com/Rising-Phoenix-Development/rpd-official-new.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-04-17T01:49:18.351Z - info: [ui] [AppStore] removing account Tgg1337 (THE Tgg1337) from store
2021-04-17T01:49:20.183Z - info: [ui] [SignInStore] initializing OAuth flow
2021-04-17T01:49:20.189Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=&scope=repo%20user%20workflow&state=
2021-04-17T01:49:21.199Z - info: [main] Received possible protocol arguments: 2
2021-04-17T01:49:21.199Z - info: [main] Processing protocol url
2021-04-17T01:49:21.200Z - info: [ui] [Dispatcher] requesting authenticated user
2021-04-17T01:49:21.914Z - info: [ui] [SignInStore] account resolved
2021-04-17T01:49:21.914Z - info: [ui] [AppStore] adding account Tgg1337 (THE Tgg1337) to store
2021-04-17T01:49:45.952Z - error: [ui] Failed to look up repository clone info for 'https://github.com/Rising-Phoenix-Development/rpd-official-new.git'
Error: Although you appear to have the correct authorization credentials, the `Rising-Phoenix-Development` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ve (/home/tay/webpack:/app/src/lib/http.ts:170:11)
    at pt.fetchRepositoryCloneInfo (/home/tay/webpack:/app/src/lib/api.ts:642:11)
    at Object.Gb.clone (/home/tay/webpack:/app/src/ui/clone-repository/clone-repository.tsx:628:11)
2021-04-17T01:49:45.953Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/Rising-Phoenix-Development/rpd-official-new.git - Tgg1337 (has token)
2021-04-17T01:51:26.556Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/Rising-Phoenix-Development/rpd-official-new.git /media/tay/Gaming HDD 1TB/Development/Bots/rpd-official-new (took 100.532s)
2021-04-17T01:51:26.565Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/Rising-Phoenix-Development/rpd-official-new.git /media/tay/Gaming HDD 1TB/Development/Bots/rpd-official-new` exited with an unexpected code: 128.
stderr:
Cloning into '/media/tay/Gaming HDD 1TB/Development/Bots/rpd-official-new'...
remote: Repository not found.
fatal: repository 'https://github.com/Rising-Phoenix-Development/rpd-official-new.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)

**Comment by shiftkey** [comment]
Please check out #281 as this is a known limitation with the current app
