### ISSUE TITLE
Error with permissions in installed files

### ISSUE THREAD

**Issue by picandocodigo** [shiftkey/desktop#5]
### Version

**GitHub Desktop version:** 4f1772350626a17d28e79af5335ed1313da39063

**OS version:** Ubuntu 16.04

### Steps to Reproduce

1. git clone from desktop/desktop
1. Follow the [installation instructions](https://github.com/desktop/desktop/blob/master/docs/contributing/setup.md#ubuntu-1604)
1. Run `yarn`, `yarn build:dev`, `yarn start`

**Expected behavior:**

When starting the app, I expect to see no errors in the console.

**Actual behavior:**

Starting the app shows this error in the console:
```
info: [ui] launching: 1.0.12-beta0 (Linux 4.4.0-103-generic)
Failed to read content scripts { Error: EACCES: permission denied, open '/home/fernando/.config/GitHub Desktop-dev/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at readArrayOfFiles (/home/fernando/workspace/picandocodigo/desktop_source/dist/desktop-linux-x64/resources/electron.asar/browser/chrome-extension.js:235:23)
    at Array.map (native)
    at contentScriptToEntry (/home/fernando/workspace/picandocodigo/desktop_source/dist/desktop-linux-x64/resources/electron.asar/browser/chrome-extension.js:242:21)
    at Array.map (native)
    at injectContentScripts (/home/fernando/workspace/picandocodigo/desktop_source/dist/desktop-linux-x64/resources/electron.asar/browser/chrome-extension.js:250:48)
    at loadExtension (/home/fernando/workspace/picandocodigo/desktop_source/dist/desktop-linux-x64/resources/electron.asar/browser/chrome-extension.js:279:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/fernando/.config/GitHub Desktop-dev/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
```

Also, if I `cd` into `~/.config/GitHub Desktop-dev/extensions/fmkadmapgofadopljbjfkapdkoienihi` I can see an issue with installed files:
```
$ ls -la build/
ls: cannot access 'build/contentScript.js': Permission denied
ls: cannot access 'build/..': Permission denied
ls: cannot access 'build/panel.js': Permission denied
ls: cannot access 'build/background.js': Permission denied
ls: cannot access 'build/main.js': Permission denied
ls: cannot access 'build/inject.js': Permission denied
ls: cannot access 'build/backend.js': Permission denied
ls: cannot access 'build/.': Permission denied
total 0
d????????? ? ? ? ?            ? .
d????????? ? ? ? ?            ? ..
-????????? ? ? ? ?            ? backend.js
-????????? ? ? ? ?            ? background.js
-????????? ? ? ? ?            ? contentScript.js
-????????? ? ? ? ?            ? inject.js
-????????? ? ? ? ?            ? main.js
-????????? ? ? ? ?            ? panel.js
```

**Reproduces how often:** 100%

### Logs
```
fernando@cultivate-xps ~/.config/GitHub Desktop-dev/logs 10:08:08
$ cat 2017-12-14.desktop.development.log 
2017-12-14T09:57:24.735Z - info: [ui] [AppStore] loading 0 repositories from store
2017-12-14T09:57:24.770Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-12-14T09:57:24.779Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-12-14T09:57:24.944Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-12-14T09:57:25.029Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-12-14T09:57:25.126Z - info: [ui] launching: 1.0.12-beta0 (Linux 4.4.0-103-generic)
2017-12-14T09:57:25.224Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-12-14T09:57:27.435Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-12-14T09:57:32.655Z - info: [ui] [Welcome] advancing to step: SignInToDotCom
2017-12-14T09:57:32.662Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2017-12-14T09:57:37.609Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2017-12-14T09:57:38.426Z - info: [ui] [AppStore] adding account picandocodigo (Fernando Briano) to store
2017-12-14T09:57:38.436Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2017-12-14T09:57:38.604Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-12-14T09:57:38.665Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-12-14T09:57:46.904Z - info: [ui] [Welcome] advancing to step: UsageOptOut
```

#### Additional Information
I searched for this error and it seems related to electron.
- LN-Zap/zap-desktop fixed it [here](https://github.com/LN-Zap/zap-desktop/pull/91)
- MarshallOfSound/electron-devtools-installer [here](https://github.com/MarshallOfSound/electron-devtools-installer/pull/64)

**Comment by shiftkey** [comment]
Yeah, this is probably related to some extension that we use in development mode. I see the same thing in macOS when running it in development mode.

Low priority for me, but if someone figures it out I'd love to hear more.

**Comment by ziggy42** [comment]
Same on Fedora 27, but everything seems to work fine

**Comment by picandocodigo** [comment]
Yep, everything seems to be working fine so I guess this will be fixed once dependencies are updated.

**Comment by shiftkey** [comment]
Sounds like updating `electron-devtools-installer` needs an update here: https://github.com/desktop/desktop/blob/master/app/package.json#L59

It's a `devDependency`, so it doesn't _really_ affect the app - you just don't get to see the right tab.

Tips for working with `yarn` are here, if someone wants to take a shot at it: https://github.com/desktop/desktop/blob/master/docs/contributing/working-with-packages.md
