### ISSUE TITLE
Clone repository could not be done.

### ISSUE THREAD

**Issue by Peregrinusz** [shiftkey/desktop#574]
### Describe the bug

A clear and concise description of what the bug is:

I cannot clone repository, that I have invited to. I tried to clone it by terminal, but could not push it. I tried to clone it on the GitHub.com tab, but the software do not show that repository. Also tried to use the URL tab, but that wrote that There was an authentication error, and ask my username and password. I typed it, but write error and ask my datas again.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

Version: 2.6.3-linux1
OS: Ubuntu Studio 20.04.2 LTS

### Steps to reproduce the behavior

I have applied the invitation a project on GitHub classroom. I have tried to clone repository, but I could not do it. 

1. Go to 'clone repository'
2. Click on 'GitHub.com tab'
3. I did not see the repo, that should be cloned to.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
2021-08-05T11:57:46.658Z - info: [ui] [AppStore] loading 3 repositories from store
2021-08-05T11:57:46.660Z - info: [ui] [AppStore] found account: Peregrinusz (Peregrinusz)
2021-08-05T11:57:46.891Z - info: [ui] [BranchPruner] Last prune took place in 9 hours - skipping
2021-08-05T11:57:48.103Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.252s)
2021-08-05T11:57:48.105Z - info: [ui] Executing getRemotes: git remote -v (took 1.105s)
2021-08-05T11:57:48.109Z - info: [ui] Executing getRemotes: git remote -v (took 1.377s)
2021-08-05T11:57:50.051Z - info: [ui] launching: 2.6.3-linux1 (Linux 5.4.0-80-lowlatency)
2021-08-05T11:57:50.052Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
2021-08-05T11:58:12.940Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.126s)
2021-08-05T12:00:10.985Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 2 repositories took 0.3s of which 0.0s paused, total 0.3s
2021-08-05T12:00:18.159Z - error: [ui] Failed to look up canonical clone url for 'https://github.com/green-fox-academy/github-quiz-Peregrinusz.git'
Error: Although you appear to have the correct authorization credentials, the `green-fox-academy` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ve (/home/pata/webpack:/app/src/lib/http.ts:170:11)
    at ut.fetchRepositoryCloneUrl (/home/pata/webpack:/app/src/lib/api.ts:620:11)
    at qv.resolveCloneURL (/home/pata/webpack:/app/src/ui/clone-repository/clone-repository.tsx:614:7)
    at Object.clone [as onSubmit] (/home/pata/webpack:/app/src/ui/clone-repository/clone-repository.tsx:631:11)
2021-08-05T12:00:18.161Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/green-fox-academy/github-quiz-Peregrinusz.git - Peregrinusz (has token)
2021-08-05T12:00:19.816Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/green-fox-academy/github-quiz-Peregrinusz.git /home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz (took 1.493s)
2021-08-05T12:00:19.820Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/green-fox-academy/github-quiz-Peregrinusz.git /home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz` exited with an unexpected code: 128.
stderr:
Cloning into '/home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz'...
remote: Repository not found.
fatal: repository 'https://github.com/green-fox-academy/github-quiz-Peregrinusz.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-08-05T12:01:02.525Z - info: [ui] storing generic credentials for 'github.com' and 'Peregrinusz'
2021-08-05T12:01:02.669Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/green-fox-academy/github-quiz-Peregrinusz.git - Peregrinusz (has token)
2021-08-05T12:01:04.128Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/green-fox-academy/github-quiz-Peregrinusz.git /home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz (took 1.419s)
2021-08-05T12:01:04.130Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/green-fox-academy/github-quiz-Peregrinusz.git /home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz` exited with an unexpected code: 128.
stderr:
Cloning into '/home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz'...
remote: Repository not found.
fatal: repository 'https://github.com/green-fox-academy/github-quiz-Peregrinusz.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-08-05T12:01:42.125Z - info: [ui] storing generic credentials for 'github.com' and 'peregrinusz'
2021-08-05T12:01:42.271Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/green-fox-academy/github-quiz-Peregrinusz.git - Peregrinusz (has token)
2021-08-05T12:01:43.306Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/green-fox-academy/github-quiz-Peregrinusz.git /home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz` exited with an unexpected code: 128.
stderr:
Cloning into '/home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz'...
remote: Repository not found.
fatal: repository 'https://github.com/green-fox-academy/github-quiz-Peregrinusz.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-08-05T12:04:42.747Z - error: [ui] Error performing periodic fetch for 'green-fox-academy/github-quiz-Peregrinusz'
Error: Unable to find path to repository on disk.
    at /home/pata/webpack:/app/node_modules/dugite/build/lib/git-process.js:87:39
    at exithandler (child_process.js:311:5)
    at ChildProcess.errorhandler (child_process.js:323:5)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
2021-08-05T12:04:42.835Z - info: [ui] [BranchPruner] Last prune took place in 8 hours - skipping
2021-08-05T12:04:42.870Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Although you appear to have the correct authorization credentials, the `green-fox-academy` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ve (/home/pata/webpack:/app/src/lib/http.ts:170:11)
    at ut.fetchProtectedBranches (/home/pata/webpack:/app/src/lib/api.ts:952:7)
    at Object.updateBranchProtectionsFromAPI (/home/pata/webpack:/app/src/lib/stores/app-store.ts:3291:11)
2021-08-05T12:04:42.983Z - warn: [ui] fetchAll: 'repos/green-fox-academy/github-quiz-Peregrinusz/issues?state=open' returned a 403
2021-08-05T12:04:42.989Z - warn: [ui] fetchMentionables: failed for green-fox-academy/github-quiz-Peregrinusz
Error: Although you appear to have the correct authorization credentials, the `green-fox-academy` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ve (/home/pata/webpack:/app/src/lib/http.ts:170:11)
    at ut.fetchMentionables (/home/pata/webpack:/app/src/lib/api.ts:1055:13)
    at jw.constructor.updateMentionables (/home/pata/webpack:/app/src/lib/stores/github-user-store.ts:90:11)
2021-08-05T12:04:43.033Z - warn: [ui] fetchAll: 'repos/green-fox-academy/github-quiz-Peregrinusz/pulls?state=open' returned a 403
2021-08-05T12:05:02.095Z - info: [ui] [BranchPruner] Last prune took place in 6 hours - skipping
2021-08-05T12:05:03.561Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.406s)
2021-08-05T12:05:47.617Z - warn: [ui] fetchRepository: 'green-fox-academy / github-quiz-Peregrinusz' returned a 404
2021-08-05T12:05:47.765Z - warn: [ui] fetchRepository: 'green-fox-academy / github-quiz-Peregrinusz' returned a 404
2021-08-05T12:05:47.767Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'green-fox-academy / github-quiz-Peregrinusz'
2021-08-05T12:05:47.845Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- green-fox-academy / github-quiz-Peregrinusz /home/pata/Dokumentumok/GitHub/ github-quiz-Peregrinusz` exited with an unexpected code: 128.
stderr:
fatal: repository 'green-fox-academy / github-quiz-Peregrinusz' does not exist

2021-08-05T12:05:57.520Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'green-fox-academy / github-quiz-Peregrinusz'
2021-08-05T12:05:57.601Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- green-fox-academy / github-quiz-Peregrinusz /home/pata/Dokumentumok/GitHub/ github-quiz-Peregrinusz` exited with an unexpected code: 128.
stderr:
fatal: repository 'green-fox-academy / github-quiz-Peregrinusz' does not exist

2021-08-05T12:10:32.437Z - info: [ui] [AppStore] adding repository at /home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz to store
2021-08-05T12:10:32.843Z - info: [ui] [BranchPruner] Last prune took place in 6 hours - skipping
2021-08-05T12:10:32.850Z - warn: [ui] fetchRepository: an error occurred for 'green-fox-academy/github-quiz-Peregrinusz'
Error: Although you appear to have the correct authorization credentials, the `green-fox-academy` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ve (/home/pata/webpack:/app/src/lib/http.ts:170:11)
    at ut.fetchRepository (/home/pata/webpack:/app/src/lib/api.ts:583:16)
    at Object.repositoryWithRefreshedGitHubRepository (/home/pata/webpack:/app/src/lib/stores/app-store.ts:3247:11)
    at async Promise.all (index 0)
    at Object._addRepositories (/home/pata/webpack:/app/src/lib/stores/app-store.ts:4812:31)
    at Object.Rv.addRepository [as onSubmit] (/home/pata/webpack:/app/src/ui/add-repository/add-existing-repository.tsx:203:11)
2021-08-05T12:10:33.340Z - info: [ui] [BranchPruner] Last prune took place in 8 hours - skipping
2021-08-05T12:10:33.440Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Although you appear to have the correct authorization credentials, the `green-fox-academy` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ve (/home/pata/webpack:/app/src/lib/http.ts:170:11)
    at ut.fetchProtectedBranches (/home/pata/webpack:/app/src/lib/api.ts:952:7)
    at Object.updateBranchProtectionsFromAPI (/home/pata/webpack:/app/src/lib/stores/app-store.ts:3291:11)
2021-08-05T12:10:33.486Z - warn: [ui] fetchRepository: an error occurred for 'green-fox-academy/github-quiz-Peregrinusz'
Error: Although you appear to have the correct authorization credentials, the `green-fox-academy` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ve (/home/pata/webpack:/app/src/lib/http.ts:170:11)
    at ut.fetchRepository (/home/pata/webpack:/app/src/lib/api.ts:583:16)
    at Object.repositoryWithRefreshedGitHubRepository (/home/pata/webpack:/app/src/lib/stores/app-store.ts:3247:11)
2021-08-05T12:10:33.682Z - warn: [ui] fetchAll: 'repos/green-fox-academy/github-quiz-Peregrinusz/issues?state=open' returned a 403
2021-08-05T12:10:33.879Z - warn: [ui] fetchAll: 'repos/green-fox-academy/github-quiz-Peregrinusz/pulls?state=open' returned a 403
2021-08-05T12:12:33.349Z - warn: [ui] fetchAll: 'repos/green-fox-academy/github-quiz-Peregrinusz/pulls?state=open' returned a 403
2021-08-05T12:14:35.537Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 166.243s)
2021-08-05T12:15:23.626Z - info: [ui] Executing createCommit: git commit -F - (took 48.090s)
2021-08-05T12:15:23.984Z - warn: [ui] fetchAll: 'repos/green-fox-academy/github-quiz-Peregrinusz/pulls?state=open' returned a 403
2021-08-05T12:15:24.391Z - info: [ui] [Timing] Action 'create commit' for 'green-fox-academy/github-quiz-Peregrinusz' took 215.179s
2021-08-05T12:15:28.668Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: github-quiz-Peregrinusz - Peregrinusz (has token)
2021-08-05T12:15:29.917Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 1.181s)
2021-08-05T12:15:35.968Z - warn: [ui] fetchRepository: an error occurred for 'green-fox-academy/github-quiz-Peregrinusz'
Error: Although you appear to have the correct authorization credentials, the `green-fox-academy` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ve (/home/pata/webpack:/app/src/lib/http.ts:170:11)
    at ut.fetchRepository (/home/pata/webpack:/app/src/lib/api.ts:583:16)
    at /home/pata/webpack:/app/src/lib/infer-last-push-for-repository.ts:38:13
    at Eu.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/home/pata/webpack:/app/src/lib/stores/app-store.ts:2725:11)
    at Eu.refreshAllRepositories (/home/pata/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2021-08-05T12:15:36.156Z - warn: [ui] fetchRepository: an error occurred for 'green-fox-academy/github-quiz-Peregrinusz'
Error: Although you appear to have the correct authorization credentials, the `green-fox-academy` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ve (/home/pata/webpack:/app/src/lib/http.ts:170:11)
    at ut.fetchRepository (/home/pata/webpack:/app/src/lib/api.ts:583:16)
    at /home/pata/webpack:/app/src/lib/infer-last-push-for-repository.ts:48:11
    at Eu.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/home/pata/webpack:/app/src/lib/stores/app-store.ts:2725:11)
    at Eu.refreshAllRepositories (/home/pata/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2021-08-05T12:15:36.159Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: github-quiz-Peregrinusz - Peregrinusz (has token)
2021-08-05T12:15:37.235Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/green-fox-academy/github-quiz-Peregrinusz.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-08-05T12:15:37.236Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 3 repositories took 2.1s of which 0.0s paused, total 2.1s
2021-08-05T12:17:23.599Z - warn: [ui] fetchAll: 'repos/green-fox-academy/github-quiz-Peregrinusz/pulls?state=open' returned a 403
2021-08-05T12:18:18.360Z - info: [ui] [BranchPruner] Last prune took place in 6 hours - skipping
2021-08-05T12:18:28.543Z - error: [ui] Failed to look up canonical clone url for 'https://github.com/green-fox-academy/github-quiz-Peregrinusz'
Error: Although you appear to have the correct authorization credentials, the `green-fox-academy` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ve (/home/pata/webpack:/app/src/lib/http.ts:170:11)
    at ut.fetchRepositoryCloneUrl (/home/pata/webpack:/app/src/lib/api.ts:620:11)
    at qv.resolveCloneURL (/home/pata/webpack:/app/src/ui/clone-repository/clone-repository.tsx:614:7)
    at Object.clone [as onSubmit] (/home/pata/webpack:/app/src/ui/clone-repository/clone-repository.tsx:631:11)
2021-08-05T12:18:28.545Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/green-fox-academy/github-quiz-Peregrinusz - Peregrinusz (has token)
2021-08-05T12:18:29.845Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/green-fox-academy/github-quiz-Peregrinusz /home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz (took 1.230s)
2021-08-05T12:18:29.848Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/green-fox-academy/github-quiz-Peregrinusz /home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz` exited with an unexpected code: 128.
stderr:
Cloning into '/home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz'...
remote: Repository not found.
fatal: repository 'https://github.com/green-fox-academy/github-quiz-Peregrinusz/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-08-05T12:19:32.719Z - info: [ui] storing generic credentials for 'github.com' and 'Peregrinusz'
2021-08-05T12:19:32.856Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/green-fox-academy/github-quiz-Peregrinusz - Peregrinusz (has token)
2021-08-05T12:19:34.066Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/green-fox-academy/github-quiz-Peregrinusz /home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz (took 1.155s)
2021-08-05T12:19:34.070Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/green-fox-academy/github-quiz-Peregrinusz /home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz` exited with an unexpected code: 128.
stderr:
Cloning into '/home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz'...
remote: Repository not found.
fatal: repository 'https://github.com/green-fox-academy/github-quiz-Peregrinusz/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-08-05T12:19:59.845Z - info: [ui] storing generic credentials for 'github.com' and 'Peregrinusz'
2021-08-05T12:19:59.957Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/green-fox-academy/github-quiz-Peregrinusz - Peregrinusz (has token)
2021-08-05T12:20:01.402Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/green-fox-academy/github-quiz-Peregrinusz /home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz (took 1.385s)
2021-08-05T12:20:01.405Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/green-fox-academy/github-quiz-Peregrinusz /home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz` exited with an unexpected code: 128.
stderr:
Cloning into '/home/pata/Dokumentumok/GitHub/github-quiz-Peregrinusz'...
remote: Repository not found.
fatal: repository 'https://github.com/green-fox-academy/github-quiz-Peregrinusz/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-08-05T12:39:49.667Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 2 repositories took 1.8s of which 516.1s paused, total 517.9s
2021-08-05T12:47:34.628Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 2 repositories took 0.8s of which 0.0s paused, total 0.8s

**Comment by K0-RR** [comment]
Why are you using version from February?

**Comment by shiftkey** [comment]
```
Error: Although you appear to have the correct authorization credentials, the green-fox-academy organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
at Ve (/home/pata/webpack:/app/src/lib/http.ts:170:11)
```

This is a known limitation of the Desktop build: https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization

https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547 has more details, and sadly it's not something that I can easily fix for this fork.

**Comment by shiftkey** [comment]
Please follow along with #72 which is tracking the underlying limitation for this problem.
