### ISSUE TITLE
Application becomes unresponsive shortly after yarn start

### ISSUE THREAD

**Issue by joaomlneto** [shiftkey/desktop#62]
###### (I have no idea where to ask this, so here it goes :-) probably something silly and I'm being blind...)

I've been trying to set up a development environment on my linux machine. Although it okay for the most part, I can't make it run smoothly. A summary of what I tried when following the documentation:
- `yarn test` fails integration test
- `yarn start` displays app, but becomes unresponsive after a few seconds
- `yarn build package` fails.

Branches tried (`shiftkey/desktop`):
- `master`
- `tags/release-1.3.5` (release runs fine on ubuntu 18.04)

OS is Linux Mint 19 Tara (same packages from Ubuntu 18.04) with 4.15 stable kernel:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19 Tara
Release:	19
Codename:	tara
$ uname -a
Linux HOSTNAME 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Versions seem fine; installed `yarn` using the native installer:
```
$ yarn -v
1.9.4
$ whereis yarn
yarn: /usr/bin/yarn /usr/share/yarn
$ npm -v
6.4.1
$ node -v
v8.12.0
```

`yarn` and `yarn build:dev` run fine:
```
$ git clone https://github.com/shiftkey/desktop.git desktop-linux && cd desktop-linux
$ yarn
(...)
Done in 98.54s
$ yarn build:dev
(...)
Done in 220.46s
```

<details>
<summary>Some unit tests fail *sometimes* due to my VM *sometimes* being slow.</summary>

- git/status › getStatus › Handles at least 10k untracked files without failing (34.109s)
- AppStore › can select a repository (27.683s)
- RepositorySettingsStore › deletes gitignore file when no entries provided (7.731s)

</details>

- Integration test fails -- doesn't pass `opens a window on launch`.
```
$ yarn test
  yarn run v1.9.4
  $ yarn test:unit --runInBand && yarn test:script && yarn test:integration
  $ cross-env ELECTRON_RUN_AS_NODE=1 node_modules/.bin/electron ./node_modules/jest/bin/jest --detectOpenHandles --silent --config ./jest.config.js --runInBand
   (...)
  Test Suites: 68 passed, 68 total
  Tests:       2 skipped, 553 passed, 555 total
  Snapshots:   0 total
  Time:        127.361s, estimated 219s
  $ mocha -P ./tsonfig.json -t 10000 --require ts-node/register script/changelog/test/*.ts
  (...)
  5 passing (27ms)
  $ cross-env TEST_ENV=1 ELECTRON_NO_ATTACH_CONSOLE=1 xvfb-maybe --auto-servernum -- mocha -t 30000 --require ts-node/register app/test/integration/*.ts
  
    App
      1) opens a window on launch
  
    0 passing (7s)
    1 failing
  
    1) App
         opens a window on launch:
       Error: Invalid Chai property: browserWindow
        at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:66:17)
        at Context.<anonymous> (app/test/integration/launch-test.ts:39:13)
        at <anonymous>
        at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  
  Failed with exit code: 1
  Output:
  
  error Command failed with exit code 255.
  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Launching with `yarn start` opens a window with the developer console on the right. I can click and do stuff... However, it becomes unresponsive after a 2-5 seconds (can't click on anything; no keyboard shortcuts; nothing).

Trying to pack and run unmodified also results in error. (`git checkout tags/release-1.3.5 && yarn build:prod && yarn build package`)
<details>
<summary>Output</summary>

```
$ yarn build package
yarn run v1.9.4
$ /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/.bin/build package
  • electron-builder version=20.27.1
  • writing effective config file=dist/builder-effective-config.yaml
  • rebuilding native production dependencies platform=linux arch=x64
  • rebuilding native dependency name=keytar
  • rebuilding native dependency name=registry-js
  • rebuilding native dependency name=runas
  • packaging       platform=linux arch=x64 electron=2.0.5 appOutDir=dist/linux-unpacked
Error: Application entry file "main.js" in the "/home/joaomlneto/Documents/GitHub/shiftkey/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:33:11
    at Generator.next (<anonymous>)
    at /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at checkFileInArchive (/home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/out/asar/asarFileChecker.js:78:17)
    at /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/platformPackager.ts:390:13
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.checkFileInPackage (/home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/platformPackager.ts:387:110)
    at /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/platformPackager.ts:439:16
    at Generator.next (<anonymous>)
    at /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at LinuxPackager.sanityCheckPackage (/home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/platformPackager.ts:426:70)
    at /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/platformPackager.ts:231:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at LinuxPackager.doPack (/home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/platformPackager.ts:157:165)
    at /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/platformPackager.ts:112:16
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.pack (/home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/platformPackager.ts:110:95)
    at /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/joaomlneto/Documents/GitHub/shiftkey/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/packager.ts:344:39)
    at /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/packager.ts:314:57
    at Generator.next (<anonymous>)
    at /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/packager.ts:285:133)
    at /home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (/home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/packager.ts:238:14)
    at build (/home/joaomlneto/Documents/GitHub/shiftkey/node_modules/app-builder-lib/src/index.ts:58:28)
    at build (/home/joaomlneto/Documents/GitHub/shiftkey/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/joaomlneto/Documents/GitHub/shiftkey/node_modules/electron-builder/src/cli/cli.ts:42:48)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

**Comment by joaomlneto** [comment]
> * `yarn test` depends on `yarn build:prod` because that generates an executable app - the CI platforms all do this, but maybe we should make that clearer when working locally?

`yarn build:prod && yarn test` runs fine.

This is not clear from documentation/scripts.

I'm new to `yarn`; just followed *half-blindly* whatever was in the documentation. :) 

>   `yarn build package` is not the right command to run - it should be `yarn run package`

Correct! My bad.

> * I'm not clear on why `yarn start` might be unresponsive after a while - any interesting output in the dev tools or console?

Nope (the dev console is also unresponsive
![screenshot 2018-09-18 at 15 45 54](https://user-images.githubusercontent.com/1539767/45695735-f57ea000-bb59-11e8-9acc-c1350d8fd6e1.png)

`$ yarn build:dev && yarn start`:
```
$ yarn start
yarn run v1.9.4
$ cross-env NODE_ENV=development ts-node -P script/tsconfig.json script/start.ts
Server running at http://localhost:3000
ℹ ｢atl｣: Using typescript@3.0.3 from typescript
ℹ ｢atl｣: Using tsconfig.json from /home/joaomlneto/Documents/GitHub/desktop/tsconfig.json
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Time: 7261ms
webpack built 8baef21181dbaed8f9f9 in 19744ms
info: [ui] [AppStore] loading 0 repositories from store
debug: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo
info: [ui] launching: 1.4.1-beta0 (Linux 4.15.0-34-generic)
info: [ui] execPath: '/home/joaomlneto/Documents/GitHub/desktop/dist/desktop-linux-x64/desktop'

<hangs>
```

**Comment by shiftkey** [comment]
Are you able to reproduce the hang with the [`electron-quick-start`](https://github.com/electron/electron-quick-start) sample? If so, I'm happy to help submit an issue upstream and see if the core team has an idea about diagnosing it...

**Comment by joaomlneto** [comment]
Can't reproduce it. Works fine:
```
$ git clone https://github.com/electron/electron-quick-start \
&& cd electron-quick-start && npm install && npm start
```

**Comment by shiftkey** [comment]
Which version of electron is it choosing (should be visible if you can run `process.versions` in the dev tools console)? Can you set [this version](https://github.com/electron/electron-quick-start/blob/master/package.json#L20) to `"2.0.9"` (the latest stable version, and one we'll hopefully upgrade Desktop to soon) and see if it's still repeatable?

**Comment by joaomlneto** [comment]
App still freezes *some time* after being launched. Can't select text, click menus, nor open/close/use the devtools.

Some Improvements:
- Ctrl-C in terminal is now able to end the process.
- Can resize/move window after it hangs (though renders window incorrectly). Cannot use app -- menus/text/devtools aren't *clickable*.

**Comment by joaomlneto** [comment]
Found a workaround/fix. [`$ electron --disable-gpu`](https://github.com/electron/electron/issues/13624#issuecomment-404537806) fixes it for me.

https://github.com/electron/electron/issues/12850
https://github.com/electron/electron/issues/13624

Also, I'm running in a VM. Apparently this is an issue:
https://github.com/electron/electron/issues/12380
