### ISSUE TITLE
Cant log in anymore

### ISSUE THREAD

**Issue by pgattic** [shiftkey/desktop#753]
### The problem

The app has been working for me for quite some time now, it was even working yesterday, but today I was logged out of my account, and couldnt get back in. I tried adding a new ssh key as well, as I noticed that it wasnt prompting me to unlock the keyring upon opening the app. still no dice. This is preventing me from pushing any commits. 

### Release version

Version 3.0.5-linux1 (x64) Flathub

### Operating system

KDE Neon 5.25 (Linux kernel 5.15.0-46-generic

### Log files

2022-08-25T04:35:10.825Z - error: [main] Error looking for toast activator CLSID in shortcut /home/prestonc/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/GitHub, Inc/GitHub Desktop.lnk
TypeError: i.shell.readShortcutLink is not a function
    at Q (/home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:38:29)
    at /home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:26:33
    at /home/prestonc/webpack:/[name]/app/src/main-process/notifications.ts:23:32
    at /home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55
    at Object.<anonymous> (/home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
2022-08-25T04:35:10.840Z - error: [main] Error looking for toast activator CLSID in shortcut /home/prestonc/Desktop/GitHub Desktop.lnk
TypeError: i.shell.readShortcutLink is not a function
    at Q (/home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:38:29)
    at /home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:26:33
    at /home/prestonc/webpack:/[name]/app/src/main-process/notifications.ts:23:32
    at /home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55
    at Object.<anonymous> (/home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
2022-08-25T04:35:10.840Z - error: [main] Toast activator CLSID not found in any of the shortucts. Falling back to known CLSIDs.
2022-08-25T04:35:10.840Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-08-25T04:35:13.028Z - info: [ui] [AppStore] loading 0 repositories from store
2022-08-25T04:35:13.145Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-08-25T04:35:13.162Z - info: [ui] launching: 3.0.5-linux1 (Linux 5.15.0-46-generic)
2022-08-25T04:35:13.165Z - info: [ui] execPath: '/app/github-desktop/github-desktop'
2022-08-25T04:35:13.403Z - info: [ui] Opt in reported.
2022-08-25T04:35:13.439Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-08-25T04:35:18.981Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
2022-08-25T04:35:18.983Z - info: [ui] [SignInStore] initializing OAuth flow
2022-08-25T04:35:18.990Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=0666e5e8-406c-4cef-b385-ce570532c260
2022-08-25T04:35:18.992Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2022-08-25T04:35:20.987Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2022-08-25T04:35:21.040Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2022-08-25T04:35:28.158Z - info: [main] Received possible protocol arguments: 4
2022-08-25T04:35:28.159Z - info: [main] Processing protocol url
2022-08-25T04:35:28.188Z - info: [ui] [Dispatcher] requesting authenticated user
2022-08-25T04:35:28.213Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2022-08-25T04:35:28.215Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2022-08-25T04:35:29.242Z - info: [ui] [SignInStore] account resolved
2022-08-25T04:35:29.243Z - info: [ui] [AppStore] adding account pgattic (Preston Corless) to store
2022-08-25T04:35:29.249Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2022-08-25T04:35:29.419Z - error: [ui] Error adding account 'pgattic'
Error: user interaction failed
2022-08-25T04:35:29.440Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-08-25T04:35:47.841Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-08-25T04:35:47.886Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-08-25T04:36:04.651Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-08-25T04:36:04.661Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-08-25T04:36:05.627Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-08-25T04:36:05.636Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-08-25T04:36:05.650Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-08-25T04:36:05.661Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-08-25T04:36:36.272Z - info: [ui] [AppStore] adding repository at /home/prestonc/Documents/GitHub/snake-evolved to store
2022-08-25T04:37:02.757Z - info: [ui] storing generic credentials for 'github.com' and 'pgattic'
2022-08-25T04:37:02.793Z - error: [ui] Error saving generic git credentials: pgattic@github.com
Error: user interaction failed
2022-08-25T04:42:36.541Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.2s of which 0.0s paused, total 0.2s
2022-08-25T04:42:45.605Z - error: [main] Error looking for toast activator CLSID in shortcut /home/prestonc/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/GitHub, Inc/GitHub Desktop.lnk
TypeError: i.shell.readShortcutLink is not a function
    at Q (/home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:38:29)
    at /home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:26:33
    at /home/prestonc/webpack:/[name]/app/src/main-process/notifications.ts:23:32
    at /home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55
    at Object.<anonymous> (/home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
2022-08-25T04:42:45.622Z - error: [main] Error looking for toast activator CLSID in shortcut /home/prestonc/Desktop/GitHub Desktop.lnk
TypeError: i.shell.readShortcutLink is not a function
    at Q (/home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:38:29)
    at /home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:26:33
    at /home/prestonc/webpack:/[name]/app/src/main-process/notifications.ts:23:32
    at /home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55
    at Object.<anonymous> (/home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
2022-08-25T04:42:45.622Z - error: [main] Toast activator CLSID not found in any of the shortucts. Falling back to known CLSIDs.
2022-08-25T04:42:45.622Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-08-25T04:42:46.273Z - info: [ui] [AppStore] loading 1 repositories from store
2022-08-25T04:42:47.629Z - info: [ui] launching: 3.0.5-linux1 (Linux 5.15.0-46-generic)
2022-08-25T04:42:47.630Z - info: [ui] execPath: '/app/github-desktop/github-desktop'
2022-08-25T04:42:48.034Z - info: [ui] Stats reported.
2022-08-25T04:47:00.784Z - error: [main] Error looking for toast activator CLSID in shortcut /home/prestonc/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/GitHub, Inc/GitHub Desktop.lnk
TypeError: i.shell.readShortcutLink is not a function
    at Q (/home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:38:29)
    at /home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:26:33
    at /home/prestonc/webpack:/[name]/app/src/main-process/notifications.ts:23:32
    at /home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55
    at Object.<anonymous> (/home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
2022-08-25T04:47:00.800Z - error: [main] Error looking for toast activator CLSID in shortcut /home/prestonc/Desktop/GitHub Desktop.lnk
TypeError: i.shell.readShortcutLink is not a function
    at Q (/home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:38:29)
    at /home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:26:33
    at /home/prestonc/webpack:/[name]/app/src/main-process/notifications.ts:23:32
    at /home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55
    at Object.<anonymous> (/home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
2022-08-25T04:47:00.801Z - error: [main] Toast activator CLSID not found in any of the shortucts. Falling back to known CLSIDs.
2022-08-25T04:47:00.801Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-08-25T04:47:01.415Z - info: [ui] [AppStore] loading 1 repositories from store
2022-08-25T04:47:02.748Z - info: [ui] launching: 3.0.5-linux1 (Linux 5.15.0-46-generic)
2022-08-25T04:47:02.749Z - info: [ui] execPath: '/app/github-desktop/github-desktop'
2022-08-25T04:47:10.424Z - info: [ui] [SignInStore] initializing OAuth flow
2022-08-25T04:47:10.433Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=bd7f3d8a-b9d6-4e27-b99e-496cce61118e
2022-08-25T04:47:16.030Z - info: [main] Received possible protocol arguments: 4
2022-08-25T04:47:16.035Z - info: [main] Processing protocol url
2022-08-25T04:47:16.070Z - info: [ui] [Dispatcher] requesting authenticated user
2022-08-25T04:47:17.061Z - info: [ui] [SignInStore] account resolved
2022-08-25T04:47:17.062Z - info: [ui] [AppStore] adding account pgattic (Preston Corless) to store
2022-08-25T04:47:17.110Z - error: [ui] Error adding account 'pgattic'
Error: user interaction failed
2022-08-25T04:48:30.260Z - info: [ui] [SignInStore] initializing OAuth flow
2022-08-25T04:48:30.271Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=9a194301-b5cc-4afb-bddf-77f5fae482c9
2022-08-25T04:48:37.445Z - info: [main] Received possible protocol arguments: 4
2022-08-25T04:48:37.447Z - info: [main] Processing protocol url
2022-08-25T04:48:37.456Z - info: [ui] [Dispatcher] requesting authenticated user
2022-08-25T04:48:38.278Z - info: [ui] [SignInStore] account resolved
2022-08-25T04:48:38.280Z - info: [ui] [AppStore] adding account pgattic (Preston Corless) to store
2022-08-25T04:48:38.350Z - error: [ui] Error adding account 'pgattic'
Error: user interaction failed
2022-08-25T04:55:56.934Z - error: [main] Error looking for toast activator CLSID in shortcut /home/prestonc/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/GitHub, Inc/GitHub Desktop.lnk
TypeError: i.shell.readShortcutLink is not a function
    at Q (/home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:38:29)
    at /home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:26:33
    at /home/prestonc/webpack:/[name]/app/src/main-process/notifications.ts:23:32
    at /home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55
    at Object.<anonymous> (/home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
2022-08-25T04:55:57.180Z - error: [main] Error looking for toast activator CLSID in shortcut /home/prestonc/Desktop/GitHub Desktop.lnk
TypeError: i.shell.readShortcutLink is not a function
    at Q (/home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:38:29)
    at /home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:26:33
    at /home/prestonc/webpack:/[name]/app/src/main-process/notifications.ts:23:32
    at /home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55
    at Object.<anonymous> (/home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
2022-08-25T04:55:57.180Z - error: [main] Toast activator CLSID not found in any of the shortucts. Falling back to known CLSIDs.
2022-08-25T04:55:57.180Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-08-25T04:56:00.605Z - info: [ui] [AppStore] loading 1 repositories from store
2022-08-25T04:56:01.032Z - info: [ui] launching: 3.0.5-linux1 (Linux 5.15.0-46-generic)
2022-08-25T04:56:01.034Z - info: [ui] execPath: '/app/github-desktop/github-desktop'
2022-08-25T04:56:03.115Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.095s)
2022-08-25T04:56:19.365Z - info: [ui] [SignInStore] initializing OAuth flow
2022-08-25T04:56:19.372Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=dfd3754c-cbcd-42cf-b486-618e2abc383a
2022-08-25T04:56:40.461Z - info: [main] Received possible protocol arguments: 4
2022-08-25T04:56:40.462Z - info: [main] Processing protocol url
2022-08-25T04:56:40.504Z - info: [ui] [Dispatcher] requesting authenticated user
2022-08-25T04:56:41.582Z - info: [ui] [SignInStore] account resolved
2022-08-25T04:56:41.584Z - info: [ui] [AppStore] adding account pgattic (Preston Corless) to store
2022-08-25T04:56:41.638Z - error: [ui] Error adding account 'pgattic'
Error: user interaction failed
2022-08-25T05:10:34.138Z - error: [main] Error looking for toast activator CLSID in shortcut /home/prestonc/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/GitHub, Inc/GitHub Desktop.lnk
TypeError: i.shell.readShortcutLink is not a function
    at Q (/home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:38:29)
    at /home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:26:33
    at /home/prestonc/webpack:/[name]/app/src/main-process/notifications.ts:23:32
    at /home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55
    at Object.<anonymous> (/home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
2022-08-25T05:10:34.160Z - error: [main] Error looking for toast activator CLSID in shortcut /home/prestonc/Desktop/GitHub Desktop.lnk
TypeError: i.shell.readShortcutLink is not a function
    at Q (/home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:38:29)
    at /home/prestonc/webpack:/[name]/app/src/lib/find-toast-activator-clsid.ts:26:33
    at /home/prestonc/webpack:/[name]/app/src/main-process/notifications.ts:23:32
    at /home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55
    at Object.<anonymous> (/home/prestonc/webpack:/[name]/app/src/main-process/main.ts:719:55)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
2022-08-25T05:10:34.160Z - error: [main] Toast activator CLSID not found in any of the shortucts. Falling back to known CLSIDs.
2022-08-25T05:10:34.160Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-08-25T05:10:35.004Z - info: [ui] [AppStore] loading 1 repositories from store
2022-08-25T05:10:36.168Z - info: [ui] launching: 3.0.5-linux1 (Linux 5.15.0-46-generic)
2022-08-25T05:10:36.169Z - info: [ui] execPath: '/app/github-desktop/github-desktop'
2022-08-25T05:10:43.095Z - info: [ui] [SignInStore] initializing OAuth flow
2022-08-25T05:10:43.105Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=0725f30f-2506-4b66-b1e6-b68043ff6c3a
2022-08-25T05:10:46.975Z - info: [main] Received possible protocol arguments: 4
2022-08-25T05:10:46.976Z - info: [main] Processing protocol url
2022-08-25T05:10:47.007Z - info: [ui] [Dispatcher] requesting authenticated user
2022-08-25T05:10:47.997Z - info: [ui] [SignInStore] account resolved
2022-08-25T05:10:47.998Z - info: [ui] [AppStore] adding account pgattic (Preston Corless) to store
2022-08-25T05:10:48.064Z - error: [ui] Error adding account 'pgattic'
Error: user interaction failed
2022-08-25T05:11:47.113Z - info: [ui] [SignInStore] initializing OAuth flow
2022-08-25T05:11:47.137Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=51e27956-9dc9-4100-a1a3-ae619b4334dd
2022-08-25T05:11:51.058Z - info: [main] Received possible protocol arguments: 4
2022-08-25T05:11:51.060Z - info: [main] Processing protocol url
2022-08-25T05:11:51.065Z - info: [ui] [Dispatcher] requesting authenticated user
2022-08-25T05:11:52.195Z - info: [ui] [SignInStore] account resolved
2022-08-25T05:11:52.196Z - info: [ui] [AppStore] adding account pgattic (Preston Corless) to store
2022-08-25T05:11:52.229Z - error: [ui] Error adding account 'pgattic'
Error: user interaction failed

### Screenshots

![image](https://user-images.githubusercontent.com/47119324/186580771-65c6b9d1-65fb-4af8-b2ec-c900de50b7ed.png)

**Comment by shiftkey** [comment]
This is the relevant error message:

```
2022-08-25T04:56:41.638Z - error: [ui] Error adding account 'pgattic'
Error: user interaction failed
```

This is an environmental issue where the app is not able to interact with the credential store on the OS over `dbus` so that it can store the token it receives after completing the authentication flow.

Please refer to https://github.com/shiftkey/desktop/issues/702#issuecomment-1138838913 as it has some notes from my last time I dug into this.

**Comment by richard-muvirimi** [comment]
Prolog / Rant

Ok, to anyone coming to this issue looking for a fix, I guess you have been cruising through Linux like Windoze, anyways most Linux desktop applications use keyrings to save your credentials, well, one could scan your system with node, python, and have you claim google is not secure anyways you could just as well commit your distro image to a public repo

The Answer
Setup a keyring app first so that GitHub Desktop has a place to store the credentials it gets from your browser

But but...
So you could sign in before, huh? That was before Plasma added a wallet by default, The quick fix, disable that wallet and a popup to create a wallet will show 

![Image](https://github.com/user-attachments/assets/611211fb-7aed-434e-91c1-94b5b5e85d34)

**Comment by kmturley** [comment]
In my case `KWalletManager` wasn't installed. I had to Search on Discover and install it. Then Open the wallet app and enable it.
