### ISSUE TITLE
Trouble building AUR package

### ISSUE THREAD

**Issue by alerque** [shiftkey/desktop#809]
I just fixed the recent change in default Git permissions by allowing it to access submodules from local file systems, but I'm having trouble rebuilding the package. This same version built just fine a little while back when I bumped it to the current version, but working in the same CHROOT environment it doesn't build now. I assume something in the JS ecosystem changed and moved on too far but I haven't been able to track it down.

Here's the output of a build now:

```
==> Starting prepare()...
Submodule 'app/static/common/choosealicense.com' (https://github.com/github/choosealicense.com.git) registered for path 'app/static/common/choosealicense.com'
Submodule 'app/static/common/gitignore' (https://github.com/github/gitignore.git) registered for path 'app/static/common/gitignore'
Submodule 'gemoji' (https://github.com/github/gemoji.git) registered for path 'gemoji'
Cloning into '/build/github-desktop/src/github-desktop/app/static/common/choosealicense.com'...
done.
Cloning into '/build/github-desktop/src/github-desktop/app/static/common/gitignore'...
done.
Cloning into '/build/github-desktop/src/github-desktop/gemoji'...
done.
Submodule path 'app/static/common/choosealicense.com': checked out 'd4edd14487305505af3eab98e364b9d2a86c5eec'
Submodule path 'app/static/common/gitignore': checked out 'e89e04390435f1e7628740d7b4ce1fe65ac218fd'
Submodule path 'gemoji': checked out '50865e8895c54037bf06c4c1691aa925d030a59d'
==> Starting build()...
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.2.1: The platform "linux" is incompatible with this module.
info "fsevents@2.2.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info dmg-license@1.0.11: The platform "linux" is incompatible with this module.
info "dmg-license@1.0.11" is an optional dependency and failed compatibility check. Excluding it from installation.
info iconv-corefoundation@1.1.7: The platform "linux" is incompatible with this module.
info "iconv-corefoundation@1.1.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > parallel-webpack@2.3.0" has incorrect peer dependency "webpack@^1.12.9 || ^2.2.0 || ^3.x || ^4.x".
warning " > eslint-plugin-github@4.3.7" has incorrect peer dependency "eslint@^8.0.1".
warning "eslint-plugin-github > eslint-plugin-prettier@4.2.1" has incorrect peer dependency "eslint@>=7.28.0".
[5/5] Building fresh packages...
$ ts-node -P script/tsconfig.json script/post-install.ts
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 10.83s.
Submodule 'license-list-XML' (https://github.com/spdx/license-list-XML.git) registered for path 'app/static/common/choosealicense.com/license-list-XML'
Cloning into '/build/github-desktop/src/github-desktop/app/static/common/choosealicense.com/license-list-XML'...
Submodule path 'app/static/common/choosealicense.com/license-list-XML': checked out 'b7470fcd383d59c95187af07b66b926e4ca23201'
yarn run v1.21.1
$ tsc -P script/tsconfig.json
Done in 8.69s.
Done in 86.93s.
yarn run v1.21.1
$ yarn compile:prod && cross-env NODE_ENV=production ts-node -P script/tsconfig.json script/build.ts
$ cross-env NODE_ENV=production TS_NODE_PROJECT=script/tsconfig.json NODE_OPTIONS='--max_old_space_size=4096' parallel-webpack --config app/webpack.production.ts
[WEBPACK] Building 5 targets
[WEBPACK] Started building renderer.js
[WEBPACK] Started building main.js
[WEBPACK] Started building crash.js
[WEBPACK] Started building cli.js
[WEBPACK] Started building highlighter.js
assets by path highlighter/mode/*.js 348 KiB
  asset highlighter/mode/sql.js 36.6 KiB [emitted] [minimized] (name: mode/sql) (id hint: modes) 1 related asset
  asset highlighter/mode/css.js 26.5 KiB [emitted] [minimized] (name: mode/css) (id hint: modes) 1 related asset
  asset highlighter/mode/stylus.js 25.6 KiB [emitted] [minimized] (name: mode/stylus) (id hint: modes) 1 related asset
  asset highlighter/mode/clike.js 20.3 KiB [emitted] [minimized] (name: mode/clike) (id hint: modes) 1 related asset
  asset highlighter/mode/javascript.js 16.8 KiB [emitted] [minimized] (name: mode/javascript) (id hint: modes) 1 related asset
  asset highlighter/mode/markdown.js 14.5 KiB [emitted] [minimized] (name: mode/markdown) (id hint: modes) 1 related asset
  asset highlighter/mode/php.js 13.5 KiB [emitted] [minimized] (name: mode/php) (id hint: modes) 1 related asset
  asset highlighter/mode/clojure.js 10.8 KiB [emitted] [minimized] (name: mode/clojure) (id hint: modes) 1 related asset
  asset highlighter/mode/soy.js 9.58 KiB [emitted] [minimized] (name: mode/soy) (id hint: modes) 1 related asset
  asset highlighter/mode/perl.js 9.52 KiB [emitted] [minimized] (name: mode/perl) (id hint: modes) 1 related asset
  + 47 assets
asset highlighter/common.js 19.5 KiB [emitted] [minimized] (name: common) (id hint: modes) 1 related asset
asset highlighter.js 16.2 KiB [emitted] [minimized] (name: highlighter) 1 related asset
asset highlighter/ext/elixir.js 4.68 KiB [emitted] [minimized] (name: ext/elixir) (id hint: modes) 1 related asset
runtime modules 4.58 KiB 10 modules
modules by path ./app/node_modules/codemirror/mode/ 704 KiB
  ./app/node_modules/codemirror/mode/javascript/javascript.js 37.3 KiB [built] [code generated]
  ./app/node_modules/codemirror/mode/coffeescript/coffeescript.js 9.8 KiB [built] [code generated]
  ./app/node_modules/codemirror/mode/jsx/jsx.js 5.11 KiB [built] [code generated]
  ./app/node_modules/codemirror/mode/xml/xml.js 12.9 KiB [built] [code generated]
  ./app/node_modules/codemirror/mode/htmlmixed/htmlmixed.js 5.55 KiB [built] [code generated]
  + 53 modules
modules by path ./app/node_modules/codemirror/addon/ 27.3 KiB
  ./app/node_modules/codemirror/addon/runmode/runmode.node.js 11.2 KiB [built] [code generated]
  ./app/node_modules/codemirror/addon/mode/multiplex.js 5.07 KiB [built] [code generated]
  ./app/node_modules/codemirror/addon/mode/overlay.js 3.17 KiB [built] [code generated]
  ./app/node_modules/codemirror/addon/mode/simple.js 7.85 KiB [built] [code generated]
./app/src/highlighter/index.ts 16.4 KiB [built] [code generated]
./app/node_modules/codemirror-mode-elixir/dist/codemirror-mode-elixir.m.js 4.59 KiB [built] [code generated]
webpack 5.68.0 compiled successfully in 5586 ms
[WEBPACK] Finished building highlighter.js within 5.586 seconds
asset cli.js 28.1 KiB [emitted] [minimized] (name: cli) 1 related asset
orphan modules 1.86 KiB [orphan] 5 modules
runtime modules 1.04 KiB 5 modules
cacheable modules 49.9 KiB
  modules by path ./app/node_modules/ 43.8 KiB 13 modules
  modules by path ./app/src/cli/ 6.08 KiB
    ./app/src/cli/main.ts 2.61 KiB [built] [code generated]
    ./app/src/cli/util.ts 1000 bytes [built] [code generated]
    + 2 modules
./app/src/cli/commands/ sync ^\.\/.*\.ts$ 203 bytes [built] [code generated]
external "os" 42 bytes [built] [code generated]
./app/src/cli/commands/clone.ts + 2 modules 1.22 KiB [not cacheable] [optional] [built] [code generated]
./app/src/cli/commands/open.ts + 2 modules 2.85 KiB [not cacheable] [optional] [built] [code generated]
./app/src/cli/open-desktop.ts + 1 modules 966 bytes [not cacheable] [built] [code generated]
webpack 5.68.0 compiled successfully in 22136 ms
[WEBPACK] Finished building cli.js within 22.136 seconds
asset crash.js 206 KiB [emitted] [minimized] (name: crash) 2 related assets
asset crash.css 19.1 KiB [emitted] (name: crash) 1 related asset
asset crash.html 258 bytes [emitted]
Entrypoint crash 225 KiB (1.24 MiB) = crash.css 19.1 KiB crash.js 206 KiB 2 auxiliary assets
orphan modules 272 KiB (javascript) 937 bytes (runtime) [orphan] 51 modules
runtime modules 1.04 KiB 5 modules
built modules 862 KiB (javascript) 19.1 KiB (css/mini-extract) [built]
  modules by path ./app/node_modules/ 659 KiB
    modules by path ./app/node_modules/uuid/ 2.29 KiB 3 modules
    modules by path ./app/node_modules/react/ 6.86 KiB 2 modules
    modules by path ./app/node_modules/react-dom/ 107 KiB 2 modules
    modules by path ./app/node_modules/scheduler/ 5.08 KiB 2 modules
    + 4 modules
  modules by path ./app/src/crash/ 203 KiB (javascript) 19.1 KiB (css/mini-extract)
    ./app/src/crash/index.tsx + 43 modules 203 KiB [not cacheable] [built] [code generated]
    ./app/src/crash/styles/crash.scss 50 bytes [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./app/src/crash/styles/crash.scss 19.1 KiB [built] [code generated]
webpack 5.68.0 compiled successfully in 26039 ms
[WEBPACK] Finished building crash.js within 26.039 seconds
asset main.js 269 KiB [emitted] [minimized] (name: main) 2 related assets
asset desktop-notifications.node 15.5 KiB [emitted] (auxiliary name: main)
orphan modules 143 KiB [orphan] 66 modules
runtime modules 1.04 KiB 5 modules
cacheable modules 1.02 MiB 142 modules
+ 17 modules
webpack 5.68.0 compiled successfully in 26648 ms
[WEBPACK] Finished building main.js within 26.648 seconds
Error parsing bundle asset "/build/github-desktop/src/github-desktop/out/renderer.js": no such file

No bundles were parsed. Analyzer will show only original module sizes from stats file.

Webpack Bundle Analyzer saved report to /build/github-desktop/src/github-desktop/out/renderer.report.html
[WEBPACK] Build failed after 53.134 seconds
[WEBPACK] Errors building renderer.js
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:130:10)
    at getHashDigest (/build/github-desktop/src/github-desktop/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /build/github-desktop/src/github-desktop/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/build/github-desktop/src/github-desktop/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/build/github-desktop/src/github-desktop/node_modules/file-loader/dist/index.js:29:48)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed, check /home/caleb/scratch/arch_chroot/caleb/build
```

**Comment by khaneliman** [comment]
@alerque Able to build now? I had been getting the error previously and it just built for me now.

**Comment by biyori** [comment]
I'm experiencing the same issue

```
[WEBPACK] Errors building renderer.js
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:130:10)
    at getHashDigest (/home/kyle/.cache/yay/github-desktop/src/github-desktop/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /home/kyle/.cache/yay/github-desktop/src/github-desktop/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/home/kyle/.cache/yay/github-desktop/src/github-desktop/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/home/kyle/.cache/yay/github-desktop/src/github-desktop/node_modules/file-loader/dist/index.js:29:48)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: github-desktop
```

**Comment by alerque** [comment]
@khaneliman No unfortunately the situation doesn't seem to have changed for me, I've tried lots of times ;-) Are you building in a clean CHROOT or directly on your host system?

**Comment by etiennecollin** [comment]
I can confirm. I get the same issue even after a clean build.

```
[WEBPACK] Finished building main.js within 16.305 seconds
Error parsing bundle asset "/home/etiennecollin/.cache/yay/github-desktop/src/github-desktop/out/renderer.js": no such file

No bundles were parsed. Analyzer will show only original module sizes from stats file.

Webpack Bundle Analyzer saved report to /home/etiennecollin/.cache/yay/github-desktop/src/github-desktop/out/renderer.report.html
[WEBPACK] Build failed after 35.91 seconds
[WEBPACK] Errors building renderer.js
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:130:10)
    at getHashDigest (/home/etiennecollin/.cache/yay/github-desktop/src/github-desktop/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /home/etiennecollin/.cache/yay/github-desktop/src/github-desktop/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/home/etiennecollin/.cache/yay/github-desktop/src/github-desktop/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/home/etiennecollin/.cache/yay/github-desktop/src/github-desktop/node_modules/file-loader/dist/index.js:29:48)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: github-desktop
```

**Comment by ilirius** [comment]
This problem is related to the updated openssl, node js by default works with openssl > 1.0 version, but not more than version 2. The ARCH system has openssl > 3.0 installed, which leads to the error ***digital envelope routines::unsupported***. Since I am a frontend developer, in such cases I have to add the environment variable NODE_OPTIONS=--openssl-legacy-provider. Then such a mistake goes away.

But to work correctly, you will need to edit the file in github-desktop/package.json where **compile:prod** is called. It is necessary to replace NODE_OPTIONS='--max_old_space_size=4096' with NODE_OPTIONS='--max_old_space_size=4096 --openssl-legacy-provider'.
This approach seems very strange and unacceptable.

Maybe it will help somehow.

P.S.
I apologize for my English.

**Comment by alerque** [comment]
Thank you @ilirius, that fix seems to have done the trick!

https://github.com/alerque/aur/commit/0c763c6bfdeba5c738cb9249e5b066608797fe30
