### ISSUE TITLE
RmSync is not a function

### ISSUE THREAD

**Issue by Smubge** [shiftkey/desktop#846]
### Operating System/Distribution

Which distribution of Linux are you using?
EndeavourOS 
### Installer

Which version of the app?
Which installer type?
3.2.0
github-desktop
### What happened?
When I used paru -S github-desktop and then selected default, there was an error 
`
home/smubge/.cache/yay/github-desktop/src/github-desktop/node_modules/postinstall-postinstall: Command failed.
Exit code: 1
Command: node ./run.js
Arguments: 
Directory: /home/smubge/.cache/yay/github-desktop/src/github-desktop/node_modules/postinstall-postinstall
Output:
error /home/smubge/.cache/yay/github-desktop/src/github-desktop/app/node_modules/dugite: Command failed.
Exit code: 1
Command: node ./script/download-git.js
Arguments: 
Directory: /home/smubge/.cache/yay/github-desktop/src/github-desktop/app/node_modules/dugite
Output:
Validation failed. Expected 'b08c173de92eecf653427810cbc9193efb3b39751690ec21196c79805038e738' but got '5029d41ad16684885ecaeb17832bf8dc86c2efdc51ad8605172309cbb367932d'
/home/smubge/.cache/yay/github-desktop/src/github-desktop/app/node_modules/dugite/script/download-git.js:123
          rmSync(tempFile)
          ^

ReferenceError: rmSync is not defined
    at /home/smubge/.cache/yay/github-desktop/src/github-desktop/app/node_modules/dugite/script/download-git.js:123:11
    at Hash.<anonymous> (/home/smubge/.cache/yay/github-desktop/src/github-desktop/app/node_modules/dugite/script/download-git.js:18:5)
    at Hash.emit (node:events:525:35)
    at finish (node:internal/streams/writable:756:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
error Command failed with exit code 1.
node:child_process:935
    throw err;
    ^

Error: Command failed: yarn run postinstall
error /home/smubge/.cache/yay/github-desktop/src/github-desktop/app/node_modules/dugite: Command failed.
Exit code: 1
Command: node ./script/download-git.js
Arguments: 
Directory: /home/smubge/.cache/yay/github-desktop/src/github-desktop/app/node_modules/dugite
Output:
Validation failed. Expected 'b08c173de92eecf653427810cbc9193efb3b39751690ec21196c79805038e738' but got '5029d41ad16684885ecaeb17832bf8dc86c2efdc51ad8605172309cbb367932d'
/home/smubge/.cache/yay/github-desktop/src/github-desktop/app/node_modules/dugite/script/download-git.js:123
          rmSync(tempFile)
          ^

ReferenceError: rmSync is not defined
    at /home/smubge/.cache/yay/github-desktop/src/github-desktop/app/node_modules/dugite/script/download-git.js:123:11
    at Hash.<anonymous> (/home/smubge/.cache/yay/github-desktop/src/github-desktop/app/node_modules/dugite/script/download-git.js:18:5)
    at Hash.emit (node:events:525:35)
    at finish (node:internal/streams/writable:756:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
error Command failed with exit code 1.

    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Object.<anonymous> (/home/smubge/.cache/yay/github-desktop/src/github-desktop/node_modules/postinstall-postinstall/run.js:15:5)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(366) [Uint8Array] [
      121,  97, 114, 110,  32, 114, 117, 110,  32, 118,  49,  46,
       50,  49,  46,  49,  10,  36,  32, 116, 115,  45, 110, 111,
      100, 101,  32,  45,  80,  32, 115,  99, 114, 105, 112, 116,
       47, 116, 115,  99, 111, 110, 102, 105, 103,  46, 106, 115,
      111, 110,  32, 115,  99, 114, 105, 112, 116,  47, 112, 111,
      115, 116,  45, 105, 110, 115, 116,  97, 108, 108,  46, 116,
      115,  10,  91,  49,  47,  52,  93,  32,  82, 101, 115, 111,
      108, 118, 105, 110, 103,  32, 112,  97,  99, 107,  97, 103,
      101, 115,  46,  46,
      ... 266 more items
    ],
    Buffer(1088) [Uint8Array] [
      101, 114, 114, 111, 114,  32,  47, 104, 111, 109, 101,  47,
      115, 109, 117,  98, 103, 101,  47,  46,  99,  97,  99, 104,
      101,  47, 121,  97, 121,  47, 103, 105, 116, 104, 117,  98,
       45, 100, 101, 115, 107, 116, 111, 112,  47, 115, 114,  99,
       47, 103, 105, 116, 104, 117,  98,  45, 100, 101, 115, 107,
      116, 111, 112,  47,  97, 112, 112,  47, 110, 111, 100, 101,
       95, 109, 111, 100, 117, 108, 101, 115,  47, 100, 117, 103,
      105, 116, 101,  58,  32,  67, 111, 109, 109,  97, 110, 100,
       32, 102,  97, 105,
      ... 988 more items
    ]
  ],
  pid: 139094,
  stdout: Buffer(366) [Uint8Array] [
    121,  97, 114, 110,  32, 114, 117, 110,  32, 118,  49,  46,
     50,  49,  46,  49,  10,  36,  32, 116, 115,  45, 110, 111,
    100, 101,  32,  45,  80,  32, 115,  99, 114, 105, 112, 116,
     47, 116, 115,  99, 111, 110, 102, 105, 103,  46, 106, 115,
    111, 110,  32, 115,  99, 114, 105, 112, 116,  47, 112, 111,
    115, 116,  45, 105, 110, 115, 116,  97, 108, 108,  46, 116,
    115,  10,  91,  49,  47,  52,  93,  32,  82, 101, 115, 111,
    108, 118, 105, 110, 103,  32, 112,  97,  99, 107,  97, 103,
    101, 115,  46,  46,
    ... 266 more items
  ],
  stderr: Buffer(1088) [Uint8Array] [
    101, 114, 114, 111, 114,  32,  47, 104, 111, 109, 101,  47,
    115, 109, 117,  98, 103, 101,  47,  46,  99,  97,  99, 104,
    101,  47, 121,  97, 121,  47, 103, 105, 116, 104, 117,  98,
     45, 100, 101, 115, 107, 116, 111, 112,  47, 115, 114,  99,
     47, 103, 105, 116, 104, 117,  98,  45, 100, 101, 115, 107,
    116, 111, 112,  47,  97, 112, 112,  47, 110, 111, 100, 101,
     95, 109, 111, 100, 117, 108, 101, 115,  47, 100, 117, 103,
    105, 116, 101,  58,  32,  67, 111, 109, 109,  97, 110, 100,
     32, 102,  97, 105,
    ... 988 more items
  ]
`

**Comment by Smubge** [comment]
Fixed somehow
