### ISSUE TITLE
The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

### ISSUE THREAD

**Issue by lexansoft** [shiftkey/desktop#942]
### The problem

Keep getting error:

"The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed."

It has nothing to do with repository. Pull works fine from command line or VSC 

SIgn Out / Sign In  to GitHub account does not help.

Definitely problem with the Desktop App. 

### Release version

3.3.3. RC2

### Operating system

Ubuntu latest

### Steps to reproduce the behavior

Any attempt to fetch (or clone)

### Screenshots

![image](https://github.com/shiftkey/desktop/assets/2127780/fffd8e38-fcf8-4c62-9438-96eac72d4c59)

**Comment by andygeorge** [comment]
I'm getting this too, but also on older versions (that were working for me before). I tested `3.3.1-linux1` and `3.2.7-linux1`, both returned the same error.

I wonder if something changed on the GitHub side that breaks this auth. I also couldn't seem to clone a private GH repo, even with a PAT.

**Comment by alexw-minesoft** [comment]
I am getting exactly the same issue - successfully logged into my orgainsation, I can see the repository I want to clone, but it tells me that authentication failed. I have tried using my password as well as a PAT.
I can clone the repo on the command line, but then if I try to fetch origin, or make a commit, it says: "The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed."

This was working fine recently, but I just had to reinstall my operating system.

I am using Linux Mint 21.2. Really hope that this can be fixed soon.

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

**Comment by lexansoft** [comment]
LOG:

2023-10-25T00:04:36.761Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: savva-ui - lexansoft (has token)
2023-10-25T00:04:37.059Z - warn: [ui] fetchRepository: an error occurred for 'AlexNa-Holdings/stihi-assets'
Error: Although you appear to have the correct authorization credentials, the `AlexNa-Holdings` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ft (/home/alexn/webpack:/app/src/lib/http.ts:178:11)
    at _n.fetchRepository (/home/alexn/webpack:/app/src/lib/api.ts:941:16)
    at /home/alexn/webpack:/app/src/lib/infer-last-push-for-repository.ts:38:13
    at Xa.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:3459:11)
    at Xa.refreshAllRepositories (/home/alexn/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2023-10-25T00:04:37.068Z - warn: [ui] fetchAll: 'repos/AlexNa-Holdings/savva-ui/pulls?state=open' returned a 403
2023-10-25T00:04:37.218Z - warn: [ui] fetchRepository: an error occurred for 'AlexNa-Holdings/stihi-assets'
Error: Although you appear to have the correct authorization credentials, the `AlexNa-Holdings` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ft (/home/alexn/webpack:/app/src/lib/http.ts:178:11)
    at _n.fetchRepository (/home/alexn/webpack:/app/src/lib/api.ts:941:16)
    at /home/alexn/webpack:/app/src/lib/infer-last-push-for-repository.ts:48:11
    at Xa.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:3459:11)
    at Xa.refreshAllRepositories (/home/alexn/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2023-10-25T00:04:37.219Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: stihi-assets - lexansoft (has token)
2023-10-25T00:04:37.279Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/AlexNa-Holdings/savva-ui.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2023-10-25T00:04:37.614Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/AlexNa-Holdings/stihi-assets.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2023-10-25T00:04:37.851Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Although you appear to have the correct authorization credentials, the `AlexNa-Holdings` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ft (/home/alexn/webpack:/app/src/lib/http.ts:178:11)
    at _n.fetchPushControl (/home/alexn/webpack:/app/src/lib/api.ts:1619:7)
    at ar.refreshBranchProtectionState (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:1173:39)
    at /home/alexn/webpack:/app/src/lib/stores/app-store.ts:5003:32
    at ar.withPushPullFetch (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:4517:5)
    at ar.performFetch (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:4959:5)
2023-10-25T00:04:38.044Z - info: [ui] [fetchAllRepoRulesets] unable to fetch all repo rulesets | repos/AlexNa-Holdings/savva-ui/rulesets
Error: Although you appear to have the correct authorization credentials, the `AlexNa-Holdings` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ft (/home/alexn/webpack:/app/src/lib/http.ts:178:11)
    at _n.fetchAllRepoRulesets (/home/alexn/webpack:/app/src/lib/api.ts:1689:7)
    at ar.refreshBranchProtectionState (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:1177:15)
    at /home/alexn/webpack:/app/src/lib/stores/app-store.ts:5003:32
    at ar.withPushPullFetch (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:4517:5)
    at ar.performFetch (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:4959:5)
2023-10-25T00:04:38.193Z - info: [ui] [fetchRepoRulesForBranch] unable to fetch repo rules for branch: main | repos/AlexNa-Holdings/savva-ui/rules/branches/main
Error: Although you appear to have the correct authorization credentials, the `AlexNa-Holdings` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ft (/home/alexn/webpack:/app/src/lib/http.ts:178:11)
    at _n.fetchRepoRulesForBranch (/home/alexn/webpack:/app/src/lib/api.ts:1668:7)
    at ar.refreshBranchProtectionState (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:1198:15)
    at /home/alexn/webpack:/app/src/lib/stores/app-store.ts:5003:32
    at ar.withPushPullFetch (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:4517:5)
    at ar.performFetch (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:4959:5)
2023-10-25T00:04:38.316Z - warn: [ui] fetchRepository: an error occurred for 'AlexNa-Holdings/stihi-contracts'
Error: Although you appear to have the correct authorization credentials, the `AlexNa-Holdings` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ft (/home/alexn/webpack:/app/src/lib/http.ts:178:11)
    at _n.fetchRepository (/home/alexn/webpack:/app/src/lib/api.ts:941:16)
    at /home/alexn/webpack:/app/src/lib/infer-last-push-for-repository.ts:38:13
    at Xa.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:3459:11)
    at Xa.refreshAllRepositories (/home/alexn/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2023-10-25T00:04:38.475Z - warn: [ui] fetchRepository: an error occurred for 'AlexNa-Holdings/stihi-contracts'
Error: Although you appear to have the correct authorization credentials, the `AlexNa-Holdings` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ft (/home/alexn/webpack:/app/src/lib/http.ts:178:11)
    at _n.fetchRepository (/home/alexn/webpack:/app/src/lib/api.ts:941:16)
    at /home/alexn/webpack:/app/src/lib/infer-last-push-for-repository.ts:48:11
    at Xa.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:3459:11)
    at Xa.refreshAllRepositories (/home/alexn/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2023-10-25T00:04:38.476Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: stihi-contracts - lexansoft (has token)
2023-10-25T00:04:38.574Z - warn: [ui] fetchAll: 'repos/AlexNa-Holdings/savva-ui/issues?state=open' returned a 403
2023-10-25T00:04:38.864Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/AlexNa-Holdings/stihi-contracts.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2023-10-25T00:04:39.493Z - warn: [ui] fetchRepository: an error occurred for 'cw-finance/contracts'
Error: Although you appear to have the correct authorization credentials, the `cw-finance` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ft (/home/alexn/webpack:/app/src/lib/http.ts:178:11)
    at _n.fetchRepository (/home/alexn/webpack:/app/src/lib/api.ts:941:16)
    at /home/alexn/webpack:/app/src/lib/infer-last-push-for-repository.ts:38:13
    at Xa.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:3459:11)
    at Xa.refreshAllRepositories (/home/alexn/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2023-10-25T00:04:39.648Z - warn: [ui] fetchRepository: an error occurred for 'cw-finance/contracts'
Error: Although you appear to have the correct authorization credentials, the `cw-finance` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at Ft (/home/alexn/webpack:/app/src/lib/http.ts:178:11)
    at _n.fetchRepository (/home/alexn/webpack:/app/src/lib/api.ts:941:16)
    at /home/alexn/webpack:/app/src/lib/infer-last-push-for-repository.ts:48:11
    at Xa.refreshIndicatorForRepository [as refreshRepositoryIndicators] (/home/alexn/webpack:/app/src/lib/stores/app-store.ts:3459:11)
    at Xa.refreshAllRepositories (/home/alexn/webpack:/app/src/lib/stores/helpers/repository-indicator-updater.ts:96:7)
2023-10-25T00:04:39.648Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: contracts - lexansoft (has token)
2023-10-25T00:04:40.059Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/cw-finance/contracts.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)

**Comment by shiftkey** [comment]
This is the key bit of the error:

`warn: [ui] fetchRepository: an error occurred for 'cw-finance/contracts'
Error: Although you appear to have the correct authorization credentials, the cw-finance organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/`

**Comment by lexansoft** [comment]
![image](https://github.com/shiftkey/desktop/assets/2127780/5b66c444-d5dd-4175-a3af-9937cfee6038)

I do not see how I can add the GitHub Desktop...

**Comment by shiftkey** [comment]
> I do not see how I can add the GitHub Desktop...

I believe this needs to be requested first: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps

**Comment by lexansoft** [comment]
[image: image.png]

It is all set, but the same error. I even tried to revoke access and
authorize it again, same...

Alexandre Naverniouk

**Comment by lexansoft** [comment]
Ha! When I set policy to "No restrictions" it started to work.

Alexandre Naverniouk

**Comment by lexansoft** [comment]
Anyway, thank you for your support. I think I can live with that. Just for
the information if I try to Setup application access restrictions:

[image: image.png]

I see this again:

[image: image.png]

The Desktop is not in the list and there is no way to add it.

Alexandre Naverniouk

**Comment by shiftkey** [comment]
Closing this out as resolved
