### ISSUE TITLE
How to approve organization access?

### ISSUE THREAD

**Issue by Arcalise08** [shiftkey/desktop#948]
I'm an admin of my organization. And when i login to this fork of github desktop, It has me link my account which mentions my organization with a green checkmark. But when i clone, It says im not authenticated. I saw the known issues mention something like this. And it says an admin needs to approve the app. But its not requesting anything for me to approve. Is that something i need to do? My other apps automatically submit a request when i login to them.

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

**Comment by Arcalise08** [comment]
Its not really an issue as much as it is a question.

If i remove the Third-party application access policy restrictions. Everything works perfectly. I don't want to do that as a long term solution though. And its not popping up under my organization to approve the application. I wasnt sure if there was something more I had to do so that it pops up in my Third-party application access policy screen in github.

**Comment by Arcalise08** [comment]
Heres the relevant logs

```
2023-10-22T21:37:54.844Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2023-10-22T21:37:54.867Z - info: [ui] [Welcome] no sign in step found. ignoring...
2023-10-22T21:37:54.877Z - info: [ui] [Welcome] no sign in step found. ignoring...
2023-10-22T21:37:55.101Z - info: [ui] Subscribed 'Arcalise08' to Alive channel
2023-10-22T21:38:36.934Z - error: [ui] Failed to look up repository clone info for 'https://github.com/Tiger-Correctional-Services/Core.git'
Error: Although you appear to have the correct authorization credentials, the `Tiger-Correctional-Services` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
    at _t (/home/arcalise08/webpack:/[name]/app/src/lib/http.ts:178:11)
    at gn.fetchRepositoryCloneInfo (/home/arcalise08/webpack:/[name]/app/src/lib/api.ts:789:11)
    at Object.clone [as onSubmit] (/home/arcalise08/webpack:/[name]/app/src/ui/clone-repository/clone-repository.tsx:710:11)
```


In my own OAuth applications i can see that it does have organization access

![image](https://github.com/shiftkey/desktop/assets/61042848/e6ed58e2-bf83-4f8e-b862-f9e17a451837)


But its not requesting access in my organization

![image](https://github.com/shiftkey/desktop/assets/61042848/db846524-7925-43b2-ad4c-5cff804e0d3c)

Hopefully thats enough info to figure out what the issue is. Apologizes if its something simple im missing here.

**Comment by LarveyOfficial** [comment]
Can confirm this issue still occurs, same error as stated above.

**Comment by 1vanK** [comment]
Same problem

**Comment by 1vanK** [comment]
I just can't push commits to my organizations repositories (I can push to my personal repositories). In a organization settings, I can click `Remove restrictions` button and this solves the problem. In Windows I have no this problem.

![Снимок экрана от 2023-11-18 20-51-22](https://github.com/shiftkey/desktop/assets/13021826/6d85a944-06f8-44d1-bad5-40142392f622)

I also tried clearing all permissions in my personal profile settings and authorizing the app again and allowing access to all organizations, but that didn't help.

**Comment by Arcalise08** [comment]
> I just can't push commits to my organizations repositories (I can push to my personal repositories). In a organization settings, I can click `Remove restrictions` button and this solves the problem. In Windows I have no this problem.
> 
> ![Снимок экрана от 2023-11-18 20-51-22](https://user-images.githubusercontent.com/13021826/284015044-6d85a944-06f8-44d1-bad5-40142392f622.png)
> 
> I also tried clearing all permissions in my personal profile settings and authorizing the app again and allowing access to all organizations, but that didn't help.

Yeah I did mention removing restrictions works. But if you working in a larger organization you're not going to want to leave restrictions off. That's a huge security risk

**Comment by 1vanK** [comment]
My Linux distribution is Linux Mint 21.2, if that makes any difference. Used binary: GitHubDesktop-linux-amd64-3.3.3-linux2.deb

**Comment by theofficialgman** [comment]
likely a duplicate of https://github.com/shiftkey/desktop/issues/217

**Comment by kov-lucas** [comment]
Same issue here

**Comment by Amsoht** [comment]
same issue here

**Comment by ken1th** [comment]
Still have the issue

**Comment by Arcalise08** [comment]
My issue was solved with this answer below

>  @bherbruck if it not showing in your org's third-party list then, you need to go to your Account Setting -->Integrations -->Applications -->Authorized OAuth Apps --> Click on "The GitHub Desktop Development App" --> Under Organization access sent a request to your Org's.

_Originally posted by @kailashzversal in https://github.com/desktop/desktop/issues/13226#issuecomment-1031096170_

**Comment by meeg** [comment]
When I was trying to set up GH Desktop a few months ago I had been having the same problems as everyone else - removing restrictions for all apps works but is not desirable, can't find any way to request app-specific access, if I follow [GitHub's instructions for requesting access](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps#requesting-organization-approval-for-an-oauth-app-youve-already-authorized-for-your-personal-account) I don't get a "request access" button. So I gave up, because most of my work happens in organization repos..

Today I updated GH Desktop and opened it again to give it a try, and I was having the same problems (unable to fetch/pull org repos), but then I thought to sign in+out of GitHub, and I was able to request+grant access as part of that process? To be specific:
* Go into the GH Desktop account options (File->Options, "Accounts" tab). It shows that I'm signed into Github.com.
* Sign out ("Sign out of GitHub.com" button).
* Sign in ("Sign into GitHub.com" button). It redirects to the web browser.
* I authenticate as usual. I then get a screen requesting me to authorize the app, similar to below (from https://github.com/isaacs/github/issues/731 - to be clear that issue is not relevant, it's just a good screenshot and I don't want to share my own account info). I was able to grant organization access using the buttons on this screen.

![image](https://github.com/user-attachments/assets/dc088d1a-317d-4157-ae92-d788acdd00ac)

I'm not sure if this was always a good solution, or something changed on GitHub's end. Unfortunately I can't easily test this, because I don't see an easy way to remove access (I can deny it, but I cannot get back to the original state before I requested+granted it). But maybe this will work for other people, and if it works it ought to go in the documentation under https://github.com/shiftkey/desktop/blob/linux/docs/known-issues.md#i-cannot-access-repositories-under-my-organization?

**Comment by qkrwnduf1997** [comment]
For me, this issue was resolved by revoking and regranting authority to this app.

I'm also an admin of my organization, so I went to (organization)Settings -> Thrid-party Access -> OAuth app policy
and click the phrase(link) "your own authorized applications" which leads to personal page of "Authorized OAuth Apps"

At there, you can revoke authorization of "The GitHub Desktop Development App".

After that it is pretty much same as @meeg 's solution.
Just don't forget to _press 'grant' button for the app_ and then pressing green 'authorize ~' button.
